Boards: add iMX8MM with SE050
foundriesio/docs pull request #166
Opened 2021-01-29 17:49 UTC by mwasilew

Signed-off-by: Milosz Wasilewski <milosz.wasilewski@foundries.io>

2021-01-29 17:50 UTC, doanac commented
Docs for e84703aa45739600e796515cf4c61ee0d0f07ea9 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/753/docs/artifacts/html/index.html

2021-01-29 18:26 UTC, Tim-Anderson requested changes
I suggest you add Matt as a reviewer since he is the maintainer of the docs, you might also add David as a reviewer.

2021-01-29 18:26 UTC, Tim-Anderson commented on source/reference-manual/boards/se050_imx8mm.rst
> +     imx8mqevk
this should be imx8mmevk

2021-01-29 18:26 UTC, Tim-Anderson commented on source/reference-manual/boards/se050_imx8mm.rst
> ++----------+------------+-------------+
The above table appears to be completely wrong. There is not documented J22 that I can find on the imxmevk and J22 on the se050 is a jumper block that does not appear to be wired to i2c.

2021-01-29 18:26 UTC, Tim-Anderson commented on source/reference-manual/boards/se050_imx8mm.rst
> +.. figure:: /_static/boards/imx8mmevk_J1004.png
this picture is normally the one directly out of the QSG with the J1004 highlighted

2021-01-29 18:26 UTC, Tim-Anderson commented on source/reference-manual/boards/se050_imx8mm.rst
> +.. figure:: /_static/boards/imx8mmevk_J1004_pinout.png
This picture should be zoomed in and pinouts shown like the used on the mq

2021-01-29 18:26 UTC, Tim-Anderson commented on source/reference-manual/boards/se050_imx8mm.rst
> +     imx8mqevk i2c pinout
this should be 8mm not 8mq

2021-01-29 18:54 UTC, mwasilew commented on source/reference-manual/boards/se050_imx8mm.rst
> ++----------+------------+-------------+
ouch, yes. J22 is on SE050 (at lease silk screen says so, bottom side) and this is how @rsalveti appears to connect it.

2021-01-29 19:03 UTC, mwasilew commented
I fixed all typos. Will update pictures on Monday

2021-01-29 19:04 UTC, doanac commented
Docs for 15af2b7c92e07f14c0b4a55bb175f892acf3130f are browesable at: https://ci.foundries.io/projects/fio-docs/builds/754/docs/artifacts/html/index.html

2021-02-01 18:55 UTC, mwasilew commented on source/reference-manual/boards/se050_imx8mm.rst
> +.. figure:: /_static/boards/imx8mmevk_J1004.png
there are already some descriptions and arrows. I replaced it with a bit better quality picture

2021-02-01 18:55 UTC, mwasilew commented on source/reference-manual/boards/se050_imx8mm.rst
> +.. figure:: /_static/boards/imx8mmevk_J1004_pinout.png
Done

2021-02-01 18:56 UTC, mwasilew commented
All comments addressed

2021-02-01 18:56 UTC, doanac commented
Docs for a761e97640898cbe7b236d9e271c6de826c15e34 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/756/docs/artifacts/html/index.html

2021-02-01 21:19 UTC, MatthewCroughan approved these changes
Excellent. I'm really glad you've done this so fast. I do not have an SE050ARD to test this, but will soon. No reason to prevent merging though! :+1:

2021-02-01 21:19 UTC, merged