Suggestion for QEMU sections and Factory local build
foundriesio/docs pull request #187
Opened 2021-03-25 20:37 UTC by angolini

This PR includes patches to:
* suggest reader to go to the 'Register your device' after booting a QEMU machine.
* Include the instruction on how to download and build a factory locally.

In case there is a way to avoid replicating the same text in all QEMU machine pages, please, let me know.

2021-03-25 20:38 UTC, doanac commented
Docs for 344940864f8972b83514e16606a13e20a1df1897 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/794/docs/artifacts/html/index.html

2021-03-25 21:15 UTC, MatthewCroughan commented
> In case there is a way to avoid replicating the same text in all QEMU machine pages, please, let me know.

The only way I know of is via #178, I've researched Sphinx a lot, I do not believe it's possible. You can write your own post processor and stick it in `conf.py`, but that requires knowing the ins-and-outs of Sphinx, to actually get that text into python and process it, which I do not :smile: 

A tool like [mdBook](https://github.com/rust-lang/mdBook/) lets you do this with any programming language, since it just spits the text out and lets you process it.

2021-03-25 21:20 UTC, MatthewCroughan commented
@angolini If you want to include it in all existing machine pages, the only way currently is to stick it in the `qemu-template.template` file which everything else is based upon, because of the incompleteness of RST Substitution. This means it will be limited to appearing at the top of the page, but I would prefer it this way.

2021-03-25 21:52 UTC, ricardosalveti commented on source/reference-manual/linux/linux-building.rst
> +      MACHINE=<machine-name> source setup-environment
We specified [BUILDDIR] as an option when running source setup-environment for lmp, should we add that here as well?

2021-03-25 21:53 UTC, ricardosalveti commented on source/reference-manual/linux/linux-building.rst
> +      bitbake lmp-factory-image
I would probably separate this in another subtask (e.g. build the lmp-factory-image, or building your factory image, etc).

Because at this stage the user needs to be aware that a huge build process will follow.

2021-03-25 21:57 UTC, ricardosalveti commented on source/reference-manual/linux/linux-building.rst
> +   configured to connect with the OTA server.
Technically it could connect to the OTA server (by forcing a registration), but the main issue is that there is no way to OTA update to the image that was built locally, as the publishing part only happens via our CI.

2021-03-25 21:58 UTC, ricardosalveti commented on source/reference-manual/linux/linux-building.rst
> +   configured to connect with the OTA server.
Basically anything built locally needs to be manually flashed, and there is no way for active devices to be updated to the version built locally.

2021-03-26 12:20 UTC, angolini commented on source/reference-manual/linux/linux-building.rst
> +      MACHINE=<machine-name> source setup-environment
sure

2021-03-26 12:33 UTC, angolini commented on source/reference-manual/linux/linux-building.rst
> +      bitbake lmp-factory-image
:+1:

2021-03-26 14:41 UTC, doanac commented
Docs for 6bdb6b98df012bf4545a6e05d4146a0a5e28732d are browesable at: https://ci.foundries.io/projects/fio-docs/builds/797/docs/artifacts/html/index.html

2021-03-26 14:42 UTC, angolini commented on source/reference-manual/linux/linux-building.rst
> +   configured to connect with the OTA server.
fixed somehow. proposed another version.

2021-03-26 15:01 UTC, MatthewCroughan approved these changes
Great addition, as I'm sure this is what most people will want to be building, rather than the base LmP itself.

2021-03-26 15:33 UTC, ricardosalveti commented on source/reference-manual/linux/linux-building.rst
> +3.  Install the ``<factory-name>`` meta layers using repo:
Should this line be build factory image? It is a duplicate of 2 atm.

2021-03-26 15:35 UTC, ricardosalveti commented on source/reference-manual/linux/linux-building.rst
> +   the environment is ready to build anything available.
We can say that lmp-factory-image is the suggested default image build by factories. We have it as part of meta-subscriber-overrides and it is also the default image target used by our CI (it can be customized if needed, but this should be the default).

2021-03-26 15:36 UTC, ricardosalveti requested changes
Just some minor comments.

2021-03-26 17:52 UTC, doanac commented
Docs for f2ef3cdb9c2682941512154b6b357bf4638aedf9 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/799/docs/artifacts/html/index.html

2021-03-26 17:56 UTC, vanmaegima commented on source/reference-manual/linux/linux-building.rst
> +
Just a suggestion, maybe it is worth mentioning here a similar sentence as in the "Build the lmp-base-console Image" topic:
"At the end of the build, your build artifacts will be found under deploy/images/raspberrypi3-64. The artifact you will use to flash your board is lmp-base-console-image-raspberrypi3-64.wic.gz."

2021-03-26 18:16 UTC, doanac commented
Docs for 704403fc542446b0d3b22bd90eb795408eff028b are browesable at: https://ci.foundries.io/projects/fio-docs/builds/800/docs/artifacts/html/index.html

2021-03-26 18:20 UTC, ricardosalveti approved these changes
LGTM

2021-03-26 18:23 UTC, merged