security: Update the offline signing doc
foundriesio/docs pull request #195
Opened 2021-04-05 03:51 UTC by doanac

This is updated to go into a little more detail about key rotation
and also introduce the new offline target key customers need to create.

There were a lot of "notes" that were a little distracting.
Additionally, one was no longer accurate and one was slightly
inaccurate.

Signed-off-by: Andy Doan <andy@foundries.io>

2021-04-05 03:52 UTC, doanac commented
@MatthewCroughan - this is needed for some work I'm doing for documenting the process of going to production. I think its probably good on its own,  so i've done on PR and will do some other PRs for other missing work. If it gets tedious we can do one big PR with a few commits. let me know what works for you.

2021-04-05 03:53 UTC, doanac commented
Docs for af202929f1cff14e8a49de3bd0a00000cf365a39 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/809/docs/artifacts/html/index.html

2021-04-05 10:54 UTC, angolini commented on source/reference-manual/security/offline-keys.rst
> +this file. This file **cannot be lost** or it's technically impossible
Maybe use something such as:
"In case this file is lost for any reason, it is **impossible** to make future key updates to the Factory"

2021-04-05 13:45 UTC, doanac commented on source/reference-manual/security/offline-keys.rst
> +this file. This file **cannot be lost** or it's technically impossible
thanks, that's better wording

2021-04-05 13:47 UTC, doanac commented
@MatthewCroughan   @angolini - ignore this for now. This page says to backup but it doesn't really explain *how* to do that. I think I'm going to create a new page that describes how to back up (i found myself repeating information in another go-to-prod doc i was working on) that details how to back up.

2021-04-05 14:29 UTC, doanac commented on source/reference-manual/security/offline-keys.rst
> +this file. This file **cannot be lost** or it's technically impossible
rebased on master and 5b81644 pulls in this suggestion

2021-04-05 14:29 UTC, doanac commented
Docs for db3bb28b181d5f3d61d5afe5c8c5a5017739b98c are browesable at: https://ci.foundries.io/projects/fio-docs/builds/811/docs/artifacts/html/index.html

2021-04-05 14:30 UTC, doanac commented
Docs for 5b8164483e48125e822223725edc1eeb8a7ed97e are browesable at: https://ci.foundries.io/projects/fio-docs/builds/812/docs/artifacts/html/index.html

2021-04-05 16:44 UTC, doanac commented
@MatthewCroughan @angolini - this is now ready for review.

NOTE - I need to add a new fioctl command `fioctl keys copy-targets` that i describe here. I'm doing that right now

2021-04-05 16:44 UTC, doanac commented
Docs for 5b8164483e48125e822223725edc1eeb8a7ed97e are browesable at: https://ci.foundries.io/projects/fio-docs/builds/813/docs/artifacts/html/index.html

2021-04-06 20:55 UTC, MatthewCroughan requested changes
Looks great, I learned a lot.

2021-04-06 20:55 UTC, MatthewCroughan commented on source/reference-manual/security/offline-keys.rst
> +require their targets file to be signed by two parties:
```suggestion
require their ``targets.json`` file to be signed by two parties:
```

Maybe we should always refer to targets as its literal, `targets.json` in order to drive home the point that this is the format it comes in, always, when working with Foundries.

2021-04-06 20:55 UTC, MatthewCroughan commented on source/reference-manual/security/offline-keys.rst
> +Given the importance of the offline credentials file, its recommended
```suggestion
Given the importance of the offline credentials file, it is recommended
```

2021-04-06 20:55 UTC, MatthewCroughan commented on source/reference-manual/security/offline-keys.rst
> + * The actual tarball - Basically ``cp <tarball> <path to thumb drive>``
```suggestion
 * The actual tarball - Basically ``cp <tarball> <path to backup storage media>``
```

2021-04-06 20:55 UTC, MatthewCroughan commented on source/reference-manual/security/offline-keys.rst
> +Its recommend to back up the Factory offline target signing key.
```suggestion
It is recommended to back up the Factory offline target signing key.
```

2021-04-06 20:55 UTC, MatthewCroughan commented on source/reference-manual/security/offline-keys.rst
> +new files like::
```suggestion
new files::
```

2021-04-06 21:31 UTC, doanac commented on source/reference-manual/security/offline-keys.rst
> +require their targets file to be signed by two parties:
Always seems strong. You wind up with something overly precise/verbose. In this case it probably makes sense.

2021-04-06 21:32 UTC, doanac commented on source/reference-manual/security/offline-keys.rst
> +new files like::
i think we need "similar to" or "like". The text below is not exact.

2021-04-06 21:38 UTC, doanac commented on source/reference-manual/security/offline-keys.rst
> +a Foundries.io owned target signing key trusted by the Factory.
I've made a similar change that avoids talking in first person. https://github.com/foundriesio/docs/pull/195/commits/f5db2102b1eae927a879a691e13b7f5f4bd3c6f8

2021-04-06 22:04 UTC, doanac commented
Docs for 0fc33ce8a5f82a21f3190b47c08d34bc743d5546 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/825/docs/artifacts/html/index.html

2021-04-06 22:07 UTC, doanac commented
Docs for 1887610bbcd77583ea33be434a29efafb367ca15 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/826/docs/artifacts/html/index.html

2021-04-06 22:08 UTC, doanac commented
Docs for 1887610bbcd77583ea33be434a29efafb367ca15 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/827/docs/artifacts/html/index.html

2021-04-07 12:01 UTC, MatthewCroughan approved these changes
LGTM once commits have been squashed.

2021-04-07 13:55 UTC, doanac commented
rebased on master and squashed

2021-04-07 13:56 UTC, doanac commented
Docs for 1bc0dc9c6a56e9333ce66a8f6bfbcc1d5a7fe902 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/839/docs/artifacts/html/index.html

2021-04-07 14:00 UTC, merged