Add documentation about preloaded images
foundriesio/docs pull request #198
Opened 2021-04-05 20:44 UTC by doanac

Signed-off-by: Andy Doan <andy@foundries.io>

2021-04-05 20:45 UTC, doanac commented
Docs for 4d6e5d9e8df546b5b6223ff2e431c1a01badcaa4 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/815/docs/artifacts/html/index.html

2021-04-06 07:19 UTC, mike-sul commented on source/reference-manual/linux/preloaded-images.rst
> +Foundries.io CI job is to always produce a Target. These Targets are
I am not an English native speaker and don't have a sufficient level of a gut feeling about language so the following most like is absolutely incorrect.
What confused me when I was reading this paragraph is referring to `Target` at first as a singular (a Target) then as plural (These Targets) and then as specific Target (the Target). :)

2021-04-06 07:31 UTC, mike-sul commented on source/reference-manual/linux/preloaded-images.rst
> +Creating Preloaded Images
I am not sure about this but the title `Creating Preloaded Images` sounds a bit misleading or confusing. The first thing that came to my mind when I read it is that some image is preloaded into/to something. Not sure if I have a better title though, maybe something longer `Creating System Images preloaded with Apps`  or `Creating System Images with preloaded Apps`.

2021-04-06 07:34 UTC, mike-sul commented on source/reference-manual/linux/preloaded-images.rst
> +  assemble_system_image: true
Maybe it makes sense to mention that `assemble_system_image` is to enable the generation of a system image preloaded with Apps on each container build, while without it only LmP build will produce such image?

2021-04-06 07:36 UTC, mike-sul commented on source/reference-manual/linux/preloaded-images.rst
> +quite common to have more complex workflows. For example a Factory may
Maybe, it's worth mentioning an option to shortlist apps for all branches.

2021-04-06 07:40 UTC, mike-sul commented
Perhaps, it makes sense to add a comment/note or reference to `fioctl targets image` command.

2021-04-06 16:23 UTC, doanac commented on source/reference-manual/linux/preloaded-images.rst
> +Creating Preloaded Images
I just don't know what to call it. It needs to be a short title and not a complete sentence. Maybe "Preloading Images with Containers".

2021-04-06 16:28 UTC, doanac commented on source/reference-manual/linux/preloaded-images.rst
> +  assemble_system_image: true
I've cross-referenced with the docs for it https://github.com/foundriesio/docs/pull/198/commits/dd1dac06d8cdaee653861a8ceea0e64c0ed06ae1

2021-04-06 16:28 UTC, doanac commented
Docs for dd1dac06d8cdaee653861a8ceea0e64c0ed06ae1 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/817/docs/artifacts/html/index.html

2021-04-06 16:31 UTC, doanac commented on source/reference-manual/linux/preloaded-images.rst
> +quite common to have more complex workflows. For example a Factory may
https://github.com/foundriesio/docs/pull/198/commits/04d61b30e5838e17fba6c57f36cedef48aa959eb

2021-04-06 16:32 UTC, doanac commented
Docs for 04d61b30e5838e17fba6c57f36cedef48aa959eb are browesable at: https://ci.foundries.io/projects/fio-docs/builds/818/docs/artifacts/html/index.html

2021-04-06 16:44 UTC, doanac commented
> Perhaps, it makes sense to add a comment/note or reference to fioctl targets image command. https://docs.foundries.io/latest/reference-manual/factory/fioctl/fioctl_targets_image.html

https://github.com/foundriesio/docs/pull/198/commits/2bacc670a45c2c0ad47d19e252319f91b857edee

2021-04-06 16:45 UTC, doanac commented
Docs for 2bacc670a45c2c0ad47d19e252319f91b857edee are browesable at: https://ci.foundries.io/projects/fio-docs/builds/819/docs/artifacts/html/index.html

2021-04-06 16:50 UTC, doanac commented
> I am not an English native speaker and don't have a sufficient level of a gut feeling about language so the following most like is absolutely incorrect.

@mike-sul - it was worded poorly. Hopefully this is more clear - https://github.com/foundriesio/docs/pull/198/commits/fddaf897c2fb24abd9ae2461bdced6a12349ac13

2021-04-06 16:50 UTC, doanac commented
Docs for fddaf897c2fb24abd9ae2461bdced6a12349ac13 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/820/docs/artifacts/html/index.html

2021-04-06 19:33 UTC, doanac commented
Docs for 45d6dad5135bc5e9ba648ee737f923248b909319 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/822/docs/artifacts/html/index.html

2021-04-06 21:27 UTC, MatthewCroughan requested changes

2021-04-06 21:27 UTC, MatthewCroughan commented on source/reference-manual/linux/preloaded-images.rst
> +Creating Preloaded Images
It's fine to be a complete sentence, otherwise we can't convey it, the concept is too complex, better to be clear than esoteric. 

```suggestion
Baking Containers Into the System Image
```
```suggestion
Baking Container Images Into the System Image
```
```suggestion
Preloading Container Images
```
```suggestion
Preloading Containers Into System Images
```

2021-04-06 21:27 UTC, MatthewCroughan commented on source/reference-manual/linux/preloaded-images.rst
> +without having to download container images.  This can be done by
```suggestion
without having to download container images. This can be done by
```

2021-04-06 21:27 UTC, MatthewCroughan commented on source/reference-manual/linux/preloaded-images.rst
> +the correct apps preloaded and enabled by default.
```suggestion
the specified apps preloaded and enabled by default.
```

2021-04-06 22:39 UTC, MatthewCroughan requested changes

2021-04-06 22:39 UTC, MatthewCroughan commented on source/reference-manual/linux/preloaded-images.rst
>  =========================
```suggestion
Preloading Container Images
===========================
```

I believe Sphinx will fail unless the amount of `=` is the same as the chars in the title. Oops. I hate that.

2021-04-06 22:42 UTC, MatthewCroughan requested changes

2021-04-06 22:42 UTC, MatthewCroughan commented on source/reference-manual/linux/preloaded-images.rst
> +=========================
```suggestion
Preloading Container Images
===========================
```

I believe Sphinx will fail unless the amount of `=` is the same as the chars in the title. Oops. I hate that.

This is another annoyance that will go away once we close #178 

```
Warning, treated as error:
/repo/source/reference-manual/linux/preloaded-images.rst:4:Title underline too short. 
```

2021-04-07 04:22 UTC, doanac commented
Docs for 2d15e78ac9d5ddc3c9aa81706ea94bed1f4c4136 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/835/docs/artifacts/html/index.html

2021-04-07 04:31 UTC, doanac commented
Docs for 2d15e78ac9d5ddc3c9aa81706ea94bed1f4c4136 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/836/docs/artifacts/html/index.html

2021-04-07 07:39 UTC, mike-sul approved these changes

2021-04-07 11:59 UTC, MatthewCroughan approved these changes
LGTM once commits are squashed.

2021-04-07 12:04 UTC, angolini approved these changes

2021-04-07 12:04 UTC, angolini commented on source/reference-manual/linux/preloaded-images.rst
> +    # the lmp has a special "production" branch, but it uses the container's
Does this mean "production" branch is special for all LmP factories? Or this is only for this one?

In case it's only for this example, maybe use something like "# This use case has a special ...."

2021-04-07 14:19 UTC, doanac commented on source/reference-manual/linux/preloaded-images.rst
> +    # the lmp has a special "production" branch, but it uses the container's
good point. i've rebased on master. the fix for this is commit d1693ea2b5fce481a85bf9a461ec85c13277c93c

2021-04-07 14:20 UTC, doanac commented
Docs for d1693ea2b5fce481a85bf9a461ec85c13277c93c are browesable at: https://ci.foundries.io/projects/fio-docs/builds/840/docs/artifacts/html/index.html

2021-04-07 14:22 UTC, doanac commented on source/reference-manual/linux/preloaded-images.rst
> +they normally want each Target to have a complete image that can run
9a6828cc35e838988cbbfe0b9dfdc18c6b63440e

2021-04-07 14:22 UTC, doanac commented
Docs for 9a6828cc35e838988cbbfe0b9dfdc18c6b63440e are browesable at: https://ci.foundries.io/projects/fio-docs/builds/841/docs/artifacts/html/index.html

2021-04-08 17:36 UTC, doanac commented
squashed and rebased

2021-04-08 17:37 UTC, merged

2021-04-08 17:38 UTC, doanac commented
Docs for cdb60e1938de5887358f46243722ab863a5804ef are browesable at: https://ci.foundries.io/projects/fio-docs/builds/843/docs/artifacts/html/index.html