Add documentation for manufacturing device registration
foundriesio/docs pull request #199
Opened 2021-04-06 03:36 UTC by doanac

Signed-off-by: Andy Doan <andy@foundries.io>

2021-04-06 03:37 UTC, doanac commented
@angolini - you may want to read this as well while you work through rolling out waves.

I fear this might be too terse and I've become too close to this problem to describe it adequately.

2021-04-06 04:30 UTC, doanac commented
Docs for 54a12fb325cb27341ea27b8861b8bd7fd14d6e5b are browesable at: https://ci.foundries.io/projects/fio-docs/builds/816/docs/artifacts/html/index.html

2021-04-06 08:07 UTC, mike-sul commented on source/reference-manual/security/factory-registration-ref.rst
> +a private network. This network is isolated from the internet
It's not clear how CA cert will be uploaded to the backend if the network is isolated?

2021-04-06 14:52 UTC, doanac commented on source/reference-manual/security/factory-registration-ref.rst
> +a private network. This network is isolated from the internet
The first paragraph links to the device gateway PKI document - https://docs.foundries.io/80/reference-manual/security/device-gateway.html.

2021-04-06 21:16 UTC, MatthewCroughan requested changes

2021-04-06 21:16 UTC, MatthewCroughan commented on source/reference-manual/security/factory-registration-ref.rst
> +the reference server. Each device will be created in api.foundries.io
```suggestion
the reference server. Each device will be created via api.foundries.io
```

2021-04-06 21:16 UTC, MatthewCroughan commented on source/reference-manual/security/factory-registration-ref.rst
> +   they connect.
```suggestion
 * Devices don't show up on Foundries.io until the first time
   they connect.
```

2021-04-06 21:16 UTC, MatthewCroughan commented on source/reference-manual/security/factory-registration-ref.rst
> + DEVICE_API="http://<registration refernce uri>/sign"
```suggestion
 DEVICE_API="http://<registration reference uri>/sign"
```

2021-04-06 21:16 UTC, MatthewCroughan commented on source/reference-manual/security/factory-registration-ref.rst
> + #systemctl start fioconfig
I am worried about the insertion of example code that isn't going to be tested over time so we can be warned as it begin to break. This is a general worry for the entirety of the docs. https://github.com/foundriesio/docs/issues/133 relates.

Sphinx doesn't have a great facility for this, but you can include scripts with `.. literalinclude: ../path/to/script` which would at least make it easier to identify and fix scripts in future. 

Since the docs are getting pretty big, I think it is an anti-pattern to embed scripts in the pages like this.

I do not think this matters for this PR though, since #178 is where I will address this myself by fixing the doc architecture.

2021-04-06 21:23 UTC, doanac commented on source/reference-manual/security/factory-registration-ref.rst
> + #systemctl start fioconfig
I don't see any clean solutions to showing examples like this. There's no way to really test this. As you said - its a difficulty that goes beyond this PR.

2021-04-06 21:37 UTC, MatthewCroughan commented on source/reference-manual/security/factory-registration-ref.rst
> + #systemctl start fioconfig
### > There's no way to really test this. 
The way to test it is to leverage what @mwasilew has done [here](https://github.com/mwasilew/test-definitions/blob/master/automated/linux/network-basic/network-basic.sh) for example.

We would:
1. Make a system image with a specified recipe from an otherwise blank Factory. 
2. Run it in `qemu`, and observe that the recipe we baked in has the correct outcome by ensuring that `systemctl status lmp-device-auto-register` succeeded.
3. Done

That is an integration test, I think we need it for recipes. Anything less is just leaving things to fate. 

### > I don't see any clean solutions to showing examples like this.

Providing recipes should be done as diffs, as I've already done [here](https://docs.foundries.io/latest/user-guide/configure-lmp/index.html#lmp-device-auto-register) for lmp-device-auto-register. 

Once we've moved to MkDocs, we will be able to clearly show diffs in expandable tabs with their filename as demonstrated [here.](https://squidfunk.github.io/mkdocs-material/upgrading/#changes-to-html-files_2)

![image](https://user-images.githubusercontent.com/26458780/113781305-67bf2c00-9728-11eb-99cd-56fbf11c7328.png)

2021-04-06 21:46 UTC, doanac commented on source/reference-manual/security/factory-registration-ref.rst
> + #systemctl start fioconfig
that's neat stuff. However, there's no recipe for this specific thing. A customer needs to build their own script for their specific needs. This is just inspirational shell script with a URL that doesn't work.

2021-04-06 22:00 UTC, doanac commented
Docs for b3949ab7db5a6bb61b3e2767304701f3ca90cb60 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/823/docs/artifacts/html/index.html

2021-04-06 22:03 UTC, doanac commented
Docs for b3949ab7db5a6bb61b3e2767304701f3ca90cb60 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/824/docs/artifacts/html/index.html

2021-04-06 22:37 UTC, MatthewCroughan approved these changes
LGTM once commits have been squashed.

2021-04-06 22:51 UTC, MatthewCroughan commented on source/reference-manual/security/factory-registration-ref.rst
> + #systemctl start fioconfig
> This is just inspirational shell script with a URL that doesn't work.

There is only one part of this script that the user has to fill out, which is `DEVICE_API="http://example.com/sign"`. I am not suggesting we test that. I am suggesting we test the rest of the execution of the script. An [integration test.](https://martinfowler.com/bliki/IntegrationTest.html)

If we ever moved `lmp-device-register` out of `/usr/bin`, or there is a race condition/api oddity causing issues, we would detect that something has changed and raise warnings when building the docs in CI, not errors, just warnings. Why shouldn't this be done for everything? 

What we have right now is quite brittle without testing.

2021-04-07 02:38 UTC, doanac commented on source/reference-manual/security/factory-registration-ref.rst
> + #systemctl start fioconfig
i'll leave that test to you. i don't doubt the validity, but i think there are more strategic places i need to focus my test automation efforts on.

2021-04-07 02:43 UTC, doanac commented
squashed and rebased on master

2021-04-07 04:28 UTC, doanac commented
Docs for a0253ce1389fab3a742d01546792b379911a1441 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/838/docs/artifacts/html/index.html

2021-04-07 11:41 UTC, angolini approved these changes

2021-04-07 12:04 UTC, merged