Tutorials initial
foundriesio/docs pull request #210
Opened 2021-04-26 15:34 UTC by munoz0raul

2021-04-26 15:35 UTC, doanac commented
Docs for 5e0674c145937e731e0097f626870caeb968730d are browesable at: https://ci.foundries.io/projects/fio-docs/builds/860/docs/artifacts/html/index.html

2021-04-26 15:45 UTC, angolini approved these changes

2021-04-26 16:12 UTC, vanmaegima approved these changes

2021-04-26 23:40 UTC, Tim-Anderson reviewed
A few corrections to make

2021-04-26 23:40 UTC, Tim-Anderson commented on source/tutorials/getting-started-with-docker/gs-docker-compose.rst
> +     Hello world
you might want to add a reference to the docker-compose.yml file format as a reference

2021-04-26 23:40 UTC, Tim-Anderson commented on source/tutorials/getting-started-with-docker/gs-dockerfile.rst
> +when you run the container.
you might want to add a reference to the Dockerfile format page

2021-04-26 23:40 UTC, Tim-Anderson commented on source/tutorials/creating-first-target/commit-and-push-our-changes.rst
> +In the preview tutorial :ref:`tutorial-gs-with-docker`, you have walked through
"preview" should be "previous"

2021-04-26 23:40 UTC, Tim-Anderson commented on source/tutorials/creating-first-target/find-your-build.rst
> +The last **Target** named :guilabel:`containers-devel` should be the CI job you just created.
change "last" to "latest"

2021-04-26 23:40 UTC, Tim-Anderson commented on source/tutorials/deploying-first-app/enabling-specific-applications.rst
> +
add the output from the wget command

2021-04-27 12:10 UTC, munoz0raul commented on source/getting-started/signup/index.rst
> +   will take up to **30 minute** to complete.
Maybe around 30 minutes?

2021-04-27 12:15 UTC, munoz0raul commented on source/tutorials/getting-started-with-docker/gs-docker-compose.rst
> +     Hello world
Do you mean:
https://docs.docker.com/compose/compose-file/

2021-04-27 12:15 UTC, munoz0raul commented on source/tutorials/getting-started-with-docker/gs-dockerfile.rst
> +when you run the container.
Do you mean:
https://docs.docker.com/engine/reference/builder/

2021-04-27 12:37 UTC, doanac commented
Docs for 1569869d893aceb884217a432f36e3d6f3dec451 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/863/docs/artifacts/html/index.html

2021-04-27 12:42 UTC, munoz0raul commented on source/getting-started/flash-device/index.rst
> +.. warning::
https://ci.foundries.io/projects/fio-docs/builds/863/docs/artifacts/html/getting-started/flash-device/index.html#flash-your-device

2021-04-27 12:43 UTC, munoz0raul commented on source/getting-started/signup/index.rst
> +   will take up to **30 minute** to complete.
https://ci.foundries.io/projects/fio-docs/builds/863/docs/artifacts/html/getting-started/signup/index.html#watch-your-build

2021-04-27 12:43 UTC, munoz0raul commented on source/tutorials/getting-started-with-docker/gs-dockerfile.rst
> +      Dockerfile
https://ci.foundries.io/projects/fio-docs/builds/863/docs/artifacts/html/tutorials/getting-started-with-docker/gs-dockerfile.html#dockerfile

2021-04-27 12:44 UTC, munoz0raul commented on source/tutorials/getting-started-with-docker/gs-httpd.rst
> +As mentioned above, ``Dockerfile`` will copy the ``httpd.sh`` file to your Docker image.
https://ci.foundries.io/projects/fio-docs/builds/863/docs/artifacts/html/tutorials/getting-started-with-docker/gs-httpd.html#httpd-sh

2021-04-27 12:48 UTC, doanac commented
Docs for b735c91394a861a9e6245c97e102772512705203 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/864/docs/artifacts/html/index.html

2021-04-27 12:48 UTC, munoz0raul commented on source/tutorials/getting-started-with-docker/gs-dockerfile.rst
> +when you run the container.
https://ci.foundries.io/projects/fio-docs/builds/863/docs/artifacts/html/tutorials/getting-started-with-docker/gs-dockerfile.html#dockerfile

2021-04-27 12:48 UTC, munoz0raul commented on source/tutorials/getting-started-with-docker/gs-docker-compose.rst
> +     Hello world
https://ci.foundries.io/projects/fio-docs/builds/863/docs/artifacts/html/tutorials/getting-started-with-docker/gs-docker-compose.html#docker-compose-yml

2021-04-27 12:49 UTC, munoz0raul commented on source/tutorials/creating-first-target/commit-and-push-our-changes.rst
> +In the preview tutorial :ref:`tutorial-gs-with-docker`, you have walked through
https://ci.foundries.io/projects/fio-docs/builds/863/docs/artifacts/html/tutorials/creating-first-target/commit-and-push-our-changes.html#commit-and-push-our-changes

2021-04-27 12:49 UTC, munoz0raul commented on source/tutorials/creating-first-target/find-your-build.rst
> +The last **Target** named :guilabel:`containers-devel` should be the CI job you just created.
https://ci.foundries.io/projects/fio-docs/builds/863/docs/artifacts/html/tutorials/creating-first-target/find-your-build.html#find-your-build

2021-04-27 12:50 UTC, munoz0raul commented on source/tutorials/deploying-first-app/enabling-specific-applications.rst
> +
https://ci.foundries.io/projects/fio-docs/builds/863/docs/artifacts/html/tutorials/deploying-first-app/enabling-specific-applications.html#enabling-specific-applications

2021-04-27 15:08 UTC, munoz0raul commented on source/tutorials/getting-started-with-docker/gs-httpd.rst
> +Move the file from ``shellhttpd.disabled`` to the ``shellhttpd`` folder:
https://ci.foundries.io/projects/fio-docs/builds/864/docs/artifacts/html/tutorials/getting-started-with-docker/gs-httpd.html#httpd-sh

2021-04-27 15:08 UTC, Tim-Anderson commented
yes

On Tue, Apr 27, 2021 at 5:15 AM Raul Muñoz ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In source/tutorials/getting-started-with-docker/gs-docker-compose.rst
> <https://github.com/foundriesio/docs/pull/210#discussion_r621149914>:
>
> > +.. prompt:: text
>
> +
>
> +     CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
>
> +     dbc969a5487d        shellhttpd:1.0       "/usr/local/bin/http…"   3 minutes ago       Up 3 minutes        0.0.0.0:8080->8080/tcp   shellhttpd_httpd_1
>
> +
>
> +Test the container with curl:
>
> +
>
> +.. prompt:: bash host:~$, auto
>
> +
>
> +    host:~$ curl 127.0.0.1:8080
>
> +
>
> +**Example Output**:
>
> +
>
> +.. prompt:: text
>
> +
>
> +     Hello world
>
>
> Do you mean:
> https://docs.docker.com/compose/compose-file/
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/foundriesio/docs/pull/210#discussion_r621149914>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAROSLY7XKNEJWG6WWOLZ4LTK2TGFANCNFSM43TEDEMQ>
> .
>

2021-04-27 15:08 UTC, Tim-Anderson commented
yes

On Tue, Apr 27, 2021 at 5:15 AM Raul Muñoz ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In source/tutorials/getting-started-with-docker/gs-dockerfile.rst
> <https://github.com/foundriesio/docs/pull/210#discussion_r621150131>:
>
> > +
>
> +The first line creates a layer from the latest
>
> +`Alpine Docker image <https://hub.docker.com/_/alpine>`_.
>
> +This means that your final image contains all the files
>
> +provided by this image plus your additions.
>
> +
>
> +Your first customization is in the second line. ``COPY`` adds files from your Docker client’s
>
> +current directory to your Docker image. In this case, you will copy the shell script
>
> +``httpd.sh`` to the ``/usr/local/bin/`` directory of your Docker image.
>
> +
>
> +Last but not least there is ``CMD``, these are arguments for the ``ENTRYPOINT``. In this example,
>
> +there is no ``ENTRYPOINT`` specified because the default entrypoint is enough.
>
> +
>
> +The default entrypoint is ``/bin/sh -c`` and by passing ``/usr/local/bin/httpd.sh`` as ``CMD`` you
>
> +are configuring the image to execute the command line: ``/bin/sh -c  /usr/local/bin/httpd.sh``
>
> +when you run the container.
>
>
> Do you mean:
> https://docs.docker.com/engine/reference/builder/
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/foundriesio/docs/pull/210#discussion_r621150131>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAROSL53M5LJS4GNRWSU6CLTK2THNANCNFSM43TEDEMQ>
> .
>

2021-04-27 17:58 UTC, doanac commented
Docs for a61ea44f3290908f9be9d57bf0ebb5532cdc4f7d are browesable at: https://ci.foundries.io/projects/fio-docs/builds/866/docs/artifacts/html/index.html

2021-04-27 21:13 UTC, Tim-Anderson approved these changes
LGTM

2021-04-30 20:24 UTC, angolini commented
I've read proof and I have no comments! Everything worked as expected!
LGTM

2021-04-30 22:34 UTC, doanac commented
Docs for b5768e4000b2132adc3502810be0175750b21fc0 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/869/docs/artifacts/html/index.html

2021-05-03 23:24 UTC, mike-scott requested changes
@Raul These tutorials are really good.

I know my edits seem like a lot, but they are mostly grammar issues that make these tutorials even better.  I hope you don't mind fixing them up.

Thank you for all your hard work on these.

2021-05-03 23:24 UTC, mike-scott commented on source/tutorials/getting-started-with-docker/getting-started-with-docker.rst
> +- Structure your apps inside the repository.
- "apps" -> "applications"
```
Structure your applications inside the repository.
```

2021-05-03 23:24 UTC, mike-scott commented on source/tutorials/getting-started-with-docker/getting-started-with-docker.rst
> +- Structure your apps inside the repository.
- "apps" -> "applications"
```
- Structure your applications inside the repository.
```

2021-05-03 23:24 UTC, mike-scott commented on source/tutorials/getting-started-with-docker/getting-started-with-docker.rst
> +- Run your container using docker-compose.
- Add styling
```
- Run your container using ``docker-compose``.
```

2021-05-03 23:24 UTC, mike-scott commented on source/tutorials/getting-started-with-docker/getting-started-with-docker.rst
> +   follow the instructions to flash and register your device and move to the next tutorials.
- Clarify
```
   It's not a problem if you just created your FoundriesFactory and your first build is 
   still running.  This tutorial **doesn’t require a device**. By the end, your build should 
   be finished and you can follow the instructions to flash and register your device before
   moving to next tutorials.
```

2021-05-03 23:24 UTC, mike-scott commented on source/tutorials/getting-started-with-docker/gs-docker-compose.rst
> +``docker-compose.yml`` could specify more than one at the same time.
- Clarify
```
In this example, we will launch just one image, but keep in mind that a 
``docker-compose.yml`` file could specify more than one image at the same time.
```

2021-05-03 23:24 UTC, mike-scott commented on source/tutorials/getting-started-with-docker/gs-docker-compose.rst
> +Notice that the MSG variable is now configured to use ``Hello world`` as default.
- Drop "now"
```
Notice that the MSG variable is configured to use ``Hello world`` as default.
```

2021-05-03 23:24 UTC, mike-scott commented on source/tutorials/getting-started-with-docker/gs-docker-compose.rst
> +To run your docker-compose app, execute the ``docker-compose up -d`` command.
- styling
```
To run your ``docker-compose`` application, execute the ``docker-compose up -d`` command. 
```

2021-05-03 23:24 UTC, mike-scott commented on source/tutorials/getting-started-with-docker/gs-docker-compose.rst
> +    host:~$ docker-compose up -d
- prefer long-form parameters for tutorial
```
    host:~$ docker-compose up --detach
```

2021-05-03 23:24 UTC, mike-scott commented on source/tutorials/getting-started-with-docker/gs-docker-compose.rst
> + - ``-d`` - Run containers in the background.
- clarify
```
 - ``--detach`` or ``-d`` - Run containers in the background.
```

2021-05-03 23:24 UTC, mike-scott commented on source/tutorials/getting-started-with-docker/gs-docker-compose.rst
> +Test the container with curl:
- Add styling
```
Test the container with ``curl``:
```

2021-05-03 23:24 UTC, mike-scott commented on source/tutorials/getting-started-with-docker/gs-dockerfile.rst
> +By having your ``Dockerfile`` you will be able to customize the base image.
- Clarify
```
Think of the ``Dockerfile`` as your way of customizing the base image.
```

2021-05-03 23:24 UTC, mike-scott commented on source/tutorials/getting-started-with-docker/gs-summary.rst
> +build and will deploy this application on your device.
- Clarity
```
You have learned the basic commands and structure of Docker and docker-compose 
applications.  At this point, if you just created your Factory, the initial build 
should be finished. In the next tutorial, you will commit and push your changes 
to the remote ``containers.git`` repository.  FoundriesFactory CI will then build 
and deploy this application as a **Target** which can be applied to your device.
```

2021-05-03 23:24 UTC, mike-scott commented on source/tutorials/getting-started-with-docker/gs-summary.rst
> +  return to the Getting Started and complete the section below:
- Reword
```
return to the ``Getting Started`` section and complete the following:
```

2021-05-04 00:21 UTC, munoz0raul commented on source/tutorials/deploying-first-app/configure-your-device.rst
> +That being said, an update could take from 5 minutes to 10 minutes to be triggered.
What do you think about making it simple:

```
Both applications are configured to communicate with your Factory.
That being said, an update could take up to 10 minutes to be triggered. 
This can be configured according to your product needs.
```

2021-05-04 00:50 UTC, munoz0raul commented on source/tutorials/getting-started-with-docker/extra-commands.rst
> +    host:~$ docker rm -f shellhttpd
I think I use force because if I don't I need to stop the container first. Need to double-check.

What do you prefer? Do you see any problem with forcing it?


```
docker rm shellhttpd_httpd_1
Error response from daemon: You cannot remove a running container 58ab0e1201f0129b5dfa414fbe3fdb536497c1c0d85305050a0637cb66ebc993. Stop the container before attempting removal or force remove
```


```
docker rm --force shellhttpd_httpd_1
shellhttpd_httpd_1
```

2021-05-04 01:53 UTC, doanac commented
Docs for a9d6f007669b7125723812fdc9623277069b5dc8 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/870/docs/artifacts/html/index.html

2021-05-04 05:11 UTC, mike-scott requested changes
@munoz0raul Found a few missed items.  Getting very close!

2021-05-04 05:11 UTC, mike-scott commented on source/tutorials/getting-started-with-docker/extra-commands.rst
> + - ``--force`` or ``-f`` - Force the removal of a running container (uses SIGKILL).
Can probably change this to a `TIP` (dropping `Where:`)

2021-05-04 05:11 UTC, mike-scott commented on source/tutorials/getting-started-with-docker/gs-docker-compose.rst
> +To run your ``docker-compose`` application, execute the ``docker-compose up -d`` command.
- Missed this:
```
To run your ``docker-compose`` application, execute the ``docker-compose up --detach`` command. 
```

2021-05-04 05:11 UTC, mike-scott commented on source/tutorials/getting-started-with-docker/gs-summary.rst
> +You have learned the basic commands and structure of Docker and docker-compose
- Add styling
```
You have learned the basic commands and structure of Docker and ``docker-compose``
```

2021-05-04 15:09 UTC, munoz0raul commented on source/tutorials/getting-started-with-docker/extra-commands.rst
> + - ``--force`` or ``-f`` - Force the removal of a running container (uses SIGKILL).
I think we should just drop the force information at this point.

2021-05-04 15:18 UTC, doanac commented
Docs for 38ea7b7457a2ee62888ad9e71fb5a112838e5abb are browesable at: https://ci.foundries.io/projects/fio-docs/builds/871/docs/artifacts/html/index.html

2021-05-04 18:55 UTC, mike-scott approved these changes
LGTM.  Great work!

2021-05-04 18:57 UTC, merged