configuring-and-sharing-volumes: Adding part3
foundriesio/docs pull request #212
Opened 2021-04-27 01:38 UTC by munoz0raul

2021-04-27 01:39 UTC, doanac commented
Docs for 10ea0f88fa9b718d67e6822c5f648ab27ea5b74c are browesable at: https://ci.foundries.io/projects/fio-docs/builds/862/docs/artifacts/html/index.html

2021-04-28 21:02 UTC, vanmaegima commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +You need to update the application to consume the file coming from the ``fioctl``.
maybe: This section shows how to update the...

2021-04-29 22:55 UTC, angolini approved these changes
Great tutorial! I've added few suggestions only.

2021-04-29 22:55 UTC, angolini commented on source/tutorials/configuring-and-sharing-volumes/copy-configuration-file-using-dockerfile.rst
> +use curl to test your modification:
```suggestion
use ``curl`` to test your modification:
```

2021-04-29 22:55 UTC, angolini commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +the files inside it.
```suggestion
When you share a folder the base operating system and the 
running containers will be able to see and consume 
the files inside it. This is one option to have then both to interact.
```

2021-04-29 22:55 UTC, angolini commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +In the previous chapter, you have created and copied the configuration file to
Maybe a cross reference would be better here (instead of "chapter")

2021-04-29 22:55 UTC, angolini commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +Make sure you received your update checking the latest target and the tab device
```suggestion
Make sure you received your update checking the latest target and the tab :guilabel:`Devices` 
```

2021-04-29 22:55 UTC, angolini commented on source/tutorials/configuring-and-sharing-volumes/configuration-file-for-fleet.rst
> +    host:~$ fioctl devices config set raspberrypi3-64 shellhttpd.conf="MSG=\"Hello from fioctl\""
+1

2021-04-30 16:22 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/configuration-file-for-fleet.rst
> +    host:~$ fioctl devices config set raspberrypi3-64 shellhttpd.conf="MSG=\"Hello from fioctl\""
I add the sentence:

"The following example will configure a single device; however, keep in mind that it could be used to affect a larger group of devices if associated with devices-groups. But more on that in further tutorials."

2021-04-30 21:28 UTC, angolini approved these changes
I've tested all the commands, and I add one command not working from my side. But I think it's a quick fix

2021-04-30 21:28 UTC, angolini commented on source/tutorials/configuring-and-sharing-volumes/configuration-file-for-fleet.rst
> +    device:~$ ls /var/run/secrets/
```
fio@imx8mmevk:~$ ls /var/run/secrets/
ls: cannot open directory '/var/run/secrets/': Permission denied
fio@imx8mmevk:~$ sudo ls /var/run/secrets/
shellhttpd.conf  wireguard-client  z-50-fioctl.toml

```

2021-04-30 21:49 UTC, Tim-Anderson reviewed
I think I have suggested enough to update this PR. Then you can ask Mike to review.

2021-04-30 21:49 UTC, Tim-Anderson commented on source/tutorials/configuring-and-sharing-volumes/configuring-and-sharing-volumes.rst
> +Prerequisites and Prework
remove 'and Prework' it is redundant with Prerequisite.

2021-04-30 21:49 UTC, Tim-Anderson commented on source/tutorials/configuring-and-sharing-volumes/configuration-file-for-fleet.rst
> +Configuration File for a Fleet of Devices
if you were doing this for a fleet it would not be to a specific device. I think this section is named incorrectly. Just name it dynamic configuration of  a device. and correct the rest of the paragraph.

2021-04-30 21:49 UTC, Tim-Anderson commented on source/tutorials/configuring-and-sharing-volumes/environment-variables.rst
> +Environment Variables
Not sure I understand the purpose of this piece. The previous tutorial already covered environment variables. I think you can drop this section. If you want to make the statement about change requires a re-build then make that in the summary of the previous tutorial.

2021-04-30 21:49 UTC, Tim-Anderson commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +    device:~$ docker ps -a
If you want to confirm that it is running then don't use the `-a` because that checks all containers. It may confuse the user

2021-04-30 21:49 UTC, Tim-Anderson commented on source/tutorials/configuring-and-sharing-volumes/configuring-and-sharing-volumes-summary.rst
> +This configuration file feature can be associated with the device group,
We have shown you can configure a device dynamically with the fioctl command. In the next tutorial we will show how you can configure a group of devices with the `device group` feature.

2021-04-30 21:49 UTC, Tim-Anderson commented on source/tutorials/configuring-and-sharing-volumes/configuring-and-sharing-volumes-summary.rst
> +allowing you to update not just one device but your whole fleet, accelerating
I do not think we want to mention fleet here.

2021-04-30 22:25 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/configuring-and-sharing-volumes-summary.rst
> +allowing you to update not just one device but your whole fleet, accelerating
I changed a bit the summary to adapt the new approach "Dynamic configuration"

2021-04-30 22:25 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/configuring-and-sharing-volumes-summary.rst
> +This configuration file feature can be associated with the device group,
I changed a bit the summary to adapt the new approach "Dynamic configuration"

2021-04-30 22:26 UTC, doanac commented
Docs for 25eb6ea3a6a7cd7eff031f58a17050d277827897 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/868/docs/artifacts/html/index.html

2021-04-30 22:26 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/environment-variables.rst
> +Environment Variables
removed the section!

2021-04-30 22:26 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/configuration-file-for-fleet.rst
> +Configuration File for a Fleet of Devices
I agree, changed the intro and the file name!

2021-05-04 21:20 UTC, doanac commented
Docs for 8e249cd49476dd22f3ae2f4525b3efcdda34a3c0 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/874/docs/artifacts/html/index.html

2021-05-05 19:20 UTC, vanmaegima commented on source/tutorials/configuring-and-sharing-volumes/copy-configuration-file-using-dockerfile.rst
> +folder ``shellhttpd``, side by side the ``Dockerfile``:
Maybe: Create the file ``shellhttpd.conf`` in your local container repository in the folder ``shellhttpd``, which holds your ``Dockerfile``:

2021-05-05 19:20 UTC, vanmaegima commented on source/tutorials/configuring-and-sharing-volumes/copy-configuration-file-using-dockerfile.rst
> +Edit the ``Dockerfile`` to create the ``shellhttpd`` folder and copy the configuration file inside it:
"and copy ``shellhttpd.conf`` to it"

2021-05-05 19:20 UTC, vanmaegima commented on source/tutorials/configuring-and-sharing-volumes/copy-configuration-file-using-dockerfile.rst
> +
Please double check the syntax for this block, the page output is:
`shellhttpd/Dockerfile: + .. prompt:: text

    FROM alpine

    RUN mkdir /home/shellhttpd/

    COPY shellhttpd.conf /home/shellhttpd/

    COPY httpd.sh /usr/local/bin/

    CMD [“/usr/local/bin/httpd.sh”]
`

2021-05-05 19:20 UTC, vanmaegima commented on source/tutorials/configuring-and-sharing-volumes/copy-configuration-file-using-dockerfile.rst
> +Use ``git status`` in the ``containers`` folder to verify all the changes you have done:
Maybe "Commit and push all changes done in the ``containers`` folder"

2021-05-05 19:20 UTC, vanmaegima commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +the files inside it. This is one option to have then both to interact.
"to have **them** both" or "This is one option for the host machine and the device to interact"

2021-05-05 19:20 UTC, vanmaegima commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +In the seccion ":ref:`tutorial-configuring-and-sharing-volumes-using-docker`", you have created and copied the configuration file to
**section**

2021-05-05 19:20 UTC, vanmaegima commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +``Dockerfile`` will **disappear** in this new setup.
Maybe rephrase this section changing the word 'device' as this can be misleading.
This means that the folder /var/rootdirs/home/fio/shellhttpd from your **host machine** will be mounted over the container folder /home/shellhttpd and the container folder content will be overwritten by the **host machine** folder content. Thus, as the **host machine** folder is empty, the shellhttpd.conf you copied in the Dockerfile will disappear in this new setup.

No need to keep this as bold, it was just to illustrate the words.

2021-05-05 19:20 UTC, vanmaegima commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +Let’s start changing the ``Dockerfile``, remove the default file to simplify your application:
I'm not sure I understand what "remove the default file" means. Is it something like "go back to the default file"?

2021-05-13 20:30 UTC, mike-scott requested changes

2021-05-13 20:30 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +``Dockerfile`` will **disappear** in this new setup.
Agree this needs to be rephrased for clarity.

2021-05-13 20:30 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +Make sure you received your update checking the latest target and the tab :guilabel:`Devices`
- Add styling
- "update checking" -> "update by checking"
- "and the tab Devices" -> "on the Devices tab"
```
Make sure you received your update by checking the latest **Target** on the :guilabel:`Devices` tab 
```

2021-05-13 20:30 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +Open one terminal connected to your device, check the running containers:
- Run-on sentence (add "and" between them)
```
Open one terminal connected to your device and check the running containers:
```

2021-05-13 20:30 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +Open a second terminal connected to your device, check for the folder
- Run-on sentence
```
Open a second terminal connected to your device and check for the folder 
```

2021-05-13 20:30 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +    device:~$ sudo bash -c 'printf "MSG=\"Hello from shared folder\"" > /var/rootdirs/home/fio/shellhttpd/shellhttpd.conf'
Simplify(?) with `echo` -- maybe just consistency with my previous change
```
device:~$ sudo bash -c 'echo "MSG=\"Hello from shared folder\"" > /var/rootdirs/home/fio/shellhttpd/shellhttpd.conf'
```

2021-05-13 20:30 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +     MSG=Hello world
Not sure it would show "MSG=Hello world" at this point in the tutorial.

2021-05-13 20:30 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +     MSG=Hello world
Not sure this would show "MSG=Hello world" at this point in the tutorial.

2021-05-13 20:30 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +how to dynamically update the configuration manually.
- Can drop either "dynamically" or "manually" but don't need both:
```
how to manually update the configuration while the container is running.
```

2021-05-13 20:30 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +This section shows how to update the application to consume the file coming from the ``fioctl``.
- Drop "the" in front of ``fioctl``
```
This section shows how to update the application to consume the file coming from ``fioctl``.
```

2021-05-13 20:30 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +Let’s start changing the ``Dockerfile``, remove the default file to simplify your application:
Also unclear to me.
And I think there is a missing "by" here: Let's start *by* changing the Dockerfile
I think this should be something like this?
```
Let’s start by changing the ``Dockerfile``, remove the addition of the ``shellhttpd.conf`` file to simplify your application:
```

2021-05-13 20:30 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +Edit the ``docker-compose.yml`` to share the folder ``/var/run/secrets``.
- Can be either "the docker-compose.yml file" or just "docker-compose.yml", but not "the docker-compose.yml"
```
Edit ``docker-compose.yml`` to share the folder ``/var/run/secrets``.
```

2021-05-13 20:30 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +Make sure you received your update checking the latest target and the tab device in your Factory.
- Add styling
- Re-word
```
Make sure you received your update by checking the latest **Target** on the :guilabel:`Devices` tab in your Factory.
```

2021-05-13 20:30 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +Once you receive the update, the docker log should show the new message:
Do we need to remind the user that the value was previously set with `fioctl` and that's why they are seeing this message instead of "Hello world"?

2021-05-13 20:30 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +Just to show how easy it is to update the configuration file,
I'm sort of confused here.  We've already used `fioctl` to set "Hello from fioctl" at this point.  We're doing it again?

2021-05-13 22:55 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/configuring-and-sharing-volumes.rst
> +``fioconfig`` can securely send configuration files to the platform. By using
Changed quite a bit here! Need another review!

2021-05-13 23:03 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +This section shows how to update the application to consume the file coming from the ``fioctl``.
I changed quite a lot this part!

2021-05-13 23:08 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +Just to show how easy it is to update the configuration file,
We are doing it again to reenforce fioctl config as well as show that you can change it on the fly!

2021-05-13 23:13 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +Just to show how easy it is to update the configuration file,
Changes it as well.

2021-05-13 23:18 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +Let’s start changing the ``Dockerfile``, remove the default file to simplify your application:
Changes quite a lot this introduction as well.

2021-05-13 23:28 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +     MSG=Hello world
It will because of:
```
    environment:
      MSG: "${MSG-Hello world}"
```

And the shared file wasn't created yet.

2021-05-13 23:30 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +Once you receive the update, the docker log should show the new message:
`Once you receive the update, the docker log should show the new message configured with fioctl in the previous section:`

2021-05-13 23:33 UTC, doanac commented
Docs for 70d3d6013cf2dcad839e7a17c1d56e919635319c are browesable at: https://ci.foundries.io/projects/fio-docs/builds/898/docs/artifacts/html/index.html

2021-05-14 16:39 UTC, doanac commented
Docs for 81a208dc12d35c6423e83b6b671264a6da8ec130 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/900/docs/artifacts/html/index.html

2021-05-14 22:22 UTC, Tim-Anderson reviewed
a few additional changes

2021-05-17 21:58 UTC, mike-scott requested changes

2021-05-17 21:58 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/copy-configuration-file-using-dockerfile.rst
> +folder ``shellhttpd``, which holds your ``Dockerfile``:
Now that this is cleaned up let's fix some word order issues:
```
Create the ``shellhttpd.conf`` file in your local container repository in the
``shellhttpd`` folder, which holds your ``Dockerfile``:
```

2021-05-17 21:58 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/configuring-and-sharing-volumes.rst
> +The goal is to cover different technics including ``fioctl config``.
- Spelling of technics
```
The goal is to cover different techniques including ``fioctl config``. 
```

2021-05-17 21:58 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +     = Thu Mar 25 19:01:07 UTC 2021 =============================
This date and the one below on the same page are a month apart.  I don't think we want the user to assume this takes a month :)

2021-05-17 21:58 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +is located in the device, in that case: ``/var/run/secrets/shellhttpd.conf``
- "in" -> "on"
- Simplify
```
is located on the device: ``/var/run/secrets/shellhttpd.conf``
```

2021-05-17 21:58 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +use the file ``/var/run/secrets/shellhttpd.conf``.
- Re-order
```
use the ``/var/run/secrets/shellhttpd.conf`` file.
```

2021-05-17 21:58 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +Let’s start by changing the ``Dockerfile``, remove the addition of the
- Run on sentence
```
Let’s start by changing the ``Dockerfile``.  Remove the addition of the 
```

2021-05-17 21:58 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +Edit ``docker-compose.yml`` to share the folder ``/var/run/secrets``.
- Re-order
```
Edit ``docker-compose.yml`` to share the ``/var/run/secrets`` folder.
```

2021-05-17 21:58 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +that everthing is working, update the configururation file using ``fioctl`` in your host machine:
- Clarify
- Spelling for "everthing"
- Spelling for "configururation"
- Run-on sentence
```
Let's repeat the ``fioctl config`` command used in the previous section, and confirm
that everything is working.

Update the configuration file using ``fioctl`` in your host machine:
```

2021-05-17 21:58 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +
Can we delete these 2 empty lines?

2021-05-17 22:13 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +     = Thu Mar 25 19:01:07 UTC 2021 =============================
Shoud I change to:
`     = Thu MMM DD HH:MM:SS UTC YYYY =============================
`

2021-05-17 22:21 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +     = Thu Mar 25 19:01:07 UTC 2021 =============================
Or something like this:

`     = XXX XXX XX XX:XX:XX XXX XXXX =============================
`

2021-05-18 00:04 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +     = Thu Mar 25 19:01:07 UTC 2021 =============================
Maybe let's drop these date lines.  They aren't important

2021-05-18 14:48 UTC, doanac commented
Docs for e5cc2ffd3c6b8f4f6e6255693bbacfcd0d1066ee are browesable at: https://ci.foundries.io/projects/fio-docs/builds/909/docs/artifacts/html/index.html

2021-05-18 23:22 UTC, mike-scott requested changes
Some more changes

2021-05-18 23:22 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +will be mounted over the container folder ``/home/shellhttpd``.
- "the container('s)" [name] "folder"
```
will be mounted over the container's ``/home/shellhttpd`` folder.
```

2021-05-18 23:22 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
> +``/var/rootdirs/home/fio/shellhttpd``:
- "the" [name] "folder"
```
Open a second terminal connected to your device and check for the
``/var/rootdirs/home/fio/shellhttpd`` folder:
```

2021-05-18 23:22 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +send configuration files using ``fioctl``. The section also shows, where the file
- no need for comma
```
send configuration files using ``fioctl``. The section also shows where the file 
```

2021-05-18 23:22 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +The ``shellhttpd`` application, is not using this file yet.
- no need for comma
```
The ``shellhttpd`` application is not using this file yet.
```

2021-05-18 23:22 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +use the ``/var/run/secrets/shellhttpd.conf`` file.
- "the" [name] "file"
- Reword
```
This section shows how to modify the ``docker-compose.yml`` file so that the application will
use the host machine's ``/var/run/secrets/shellhttpd.conf`` file instead of a configuration file built
into the container.
```

2021-05-18 23:22 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +Edit ``docker-compose.yml`` to share the ``/var/run/secrets`` folder.
Do we want to clarify here that the `volumes:` stanza will already exist as (from the "Sharing a Folder" page):
```
volumes:
  - /var/rootdirs/home/fio/shellhttpd:/home/shellhttpd/
```
and that they will be changing it to:
```
- /var/run/secrets:/home/shellhttpd/
```

2021-05-18 23:22 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +           - /var/run/secrets:/home/shellhttpd/
Maybe have the old value commented here?

2021-05-18 23:22 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +    host:~$ fioctl devices config set raspberrypi3-64 shellhttpd.conf="MSG=\"New Config file updated over-the-air\""
nit: New Config file updated over-the-air (with the capital C in Config looks odd to me here

2021-05-18 23:22 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +     New Config file updated over-the-air
nit: New Config file updated over-the-air (with the capital C in Config looks odd to me here

2021-05-19 19:26 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/copy-configuration-file-using-dockerfile.rst
> +    host:~$ git add shellhttpd/httpd.sh
Yes, we changed it on the previous page.

2021-05-19 19:29 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/modify-shellhttpd-container.rst
> +	     echo -en "$RESPONSE" | timeout 5 nc -l -p "${PORT}" || true
The time out was added there to reload the configuration file dynamically.

The original example doesn't use time out, it gets stuck in the nc line until receives a request. 

I just change the timeout for the parameter -w 5.

With -w 5 nc restart after wait 5 seconds and reload the config file.

2021-05-19 19:35 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +Edit ``docker-compose.yml`` to share the ``/var/run/secrets`` folder.
`Edit ``docker-compose.yml`` and change the ``volume`` stanza to share the ``/var/run/secrets`` folder.
`

2021-05-19 19:38 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +           - /var/run/secrets:/home/shellhttpd/
I don't think that is the way to go, because other files had bigger changes. If we keep all changes as comments it will get even more complicated. 

I think maybe in the future, with mkdoc we might check if there is some kind of patch style box. What do you think?

2021-05-19 21:04 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/copy-configuration-file-using-dockerfile.rst
> +    host:~$ git add shellhttpd/httpd.sh
Ah right.

2021-05-19 21:06 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/modify-shellhttpd-container.rst
> +	     echo -en "$RESPONSE" | timeout 5 nc -l -p "${PORT}" || true
Side-Note: We should also update the template used to create Factories

2021-05-19 21:09 UTC, mike-scott commented on source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst
> +           - /var/run/secrets:/home/shellhttpd/
No worries.  The clarification above this is enough.

2021-05-19 21:11 UTC, munoz0raul commented on source/tutorials/configuring-and-sharing-volumes/modify-shellhttpd-container.rst
> +	     echo -en "$RESPONSE" | timeout 5 nc -l -p "${PORT}" || true
Not really, that is customization on top of the basic one. I would add just -c on the template to cover LmP and any other machine.

2021-05-20 16:43 UTC, mike-scott commented
ci retest

2021-05-20 16:44 UTC, mike-scott commented
ci-retest

2021-05-20 17:20 UTC, munoz0raul commented
LGTM. @mike-scott I think it is time to merge this PR.

2021-05-20 19:55 UTC, mike-scott approved these changes

2021-05-20 20:02 UTC, doanac commented
Docs for 1f22fc2df71206532202034f6943df882a87fc11 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/921/docs/artifacts/html/index.html

2021-05-20 20:11 UTC, merged