compose-app-handson: Adding Tutorial
foundriesio/docs pull request #217
Opened 2021-05-10 19:45 UTC by munoz0raul

2021-05-10 19:46 UTC, doanac commented
Docs for 9e4cc3d4086e1418934e5a957fc7d14c70f2519d are browesable at: https://ci.foundries.io/projects/fio-docs/builds/889/docs/artifacts/html/index.html

2021-05-11 12:59 UTC, vanmaegima commented on source/tutorials/compose-app-handson/handson-docker-compose-apps.rst
> +That is very commun when you have an image used by multiple Docker Compose Apps.
common
Docker Container Image used by...

2021-05-11 16:46 UTC, doanac commented on source/index.rst
> +   tutorials/compose-app-handson/handson-compose-app
"hands on" feels a little weird. the filenames really confused me. I thought "hand-son"  and it was some sort of new app i'd never heard of. I think something like "Working with Compose Apps" or just "Compose Apps" would be easier to understand

2021-05-12 13:38 UTC, angolini approved these changes

2021-05-12 13:38 UTC, angolini commented on source/tutorials/compose-app-handson/handson-flask-mqtt-nginx.rst
> +is dependences.
Are line 4 describing Lask-MQTT-nginx?
I think this paragraph is confusing

2021-05-12 13:38 UTC, angolini commented on source/tutorials/compose-app-handson/handson-flask-mqtt-nginx.rst
> +     # flask-mqtt-nginx/docker-compose.yml
is this line commented on purpose?

2021-05-12 13:38 UTC, angolini commented on source/tutorials/compose-app-handson/handson-flask-mqtt-nginx.rst
> +- ``volume``: replace the default ``/etc/nginx/conf.d/default.conf`` configuration inside the Docker image with the ngix.conf file in the flask-mqtt-nginx folder.
```suggestion
- ``volume``: replace the default ``/etc/nginx/conf.d/default.conf`` configuration inside the Docker image with the ``ngix.conf`` file in the flask-mqtt-nginx folder.
```

2021-05-12 13:38 UTC, angolini commented on source/tutorials/compose-app-handson/handson-testing-applications.rst
> +Create mor access on ``shellhttpd-mqtt_httpd-mqtt_1``
I prefer Vanessa's suggestion, but only to make sure "mor" -> "more"

2021-05-12 13:38 UTC, angolini commented on source/tutorials/compose-app-handson/handson-summary.rst
> +This tutorial gives you a good overview on how the folder and files structures
```suggestion
This tutorial gives you a good overview on how the folder and files structure
```

2021-05-12 13:38 UTC, angolini commented on source/tutorials/compose-app-handson/handson-summary.rst
> +more application examples that could be used in your further development.
it also explain how to deal with dependency between containers, it also explain that you can use a docker image from docker.hub.io, or any other source.

2021-05-12 23:26 UTC, doanac commented
Docs for f88e419647a1c00bd33b755b5e209bfd68d1e1b9 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/894/docs/artifacts/html/index.html

2021-05-13 16:54 UTC, vanmaegima commented on source/tutorials/compose-app-handson/handson-flask-mqtt-nginx.rst
> +``fask-mqtt-ngix`` application is a typical python3 Flask application together with nginx.
@munoz0raul this seems to not be fixed

2021-05-13 17:00 UTC, vanmaegima commented on source/tutorials/compose-app-handson/handson-summary.rst
> +in the ``containers.git`` is important for application creation. It also gives you
@munoz0raul I guess this isn't fixed

2021-05-18 14:03 UTC, MatthewCroughan commented
Is there any reason this can't be merged? I need it in master so I can rebase #218.

2021-05-20 19:31 UTC, doanac commented
Docs for 424becbbd0b5c84bedcc02f5e67b586ecd66242e are browesable at: https://ci.foundries.io/projects/fio-docs/builds/919/docs/artifacts/html/index.html

2021-05-21 18:41 UTC, doanac commented
Docs for c38930e9fe6bb5a9061d255f2a2a3cb7386ff391 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/926/docs/artifacts/html/index.html

2021-05-25 18:26 UTC, doanac commented
Docs for 35fc832c39969d30e83311e1f90b6a2f75577308 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/934/docs/artifacts/html/index.html

2021-07-28 04:34 UTC, doanac commented
Docs for afaf15c13d70e94895a6eaaeef39be38a43bbf6f are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1003/docs/artifacts/html/index.html

2021-07-28 04:34 UTC, munoz0raul commented
@mike-scott, I just synced it with the latest fio master and tested it again. I think this is a very important one once Switch-EV could use it to get started with FF.

2021-07-28 15:54 UTC, doanac commented on source/tutorials/compose-app/compose-app-file-structure.rst
> +present in the same folder.
```suggestion
What is important in the example is the ``shellhttpd`` directory containing 
a ``docker-compose.yml`` and a ``Dockerfile`` file. CI will produce both a Docker Container image and Compose app named ``shellhttpd``
```

2021-07-28 15:54 UTC, doanac commented on source/tutorials/compose-app/compose-app-flask-mqtt-nginx.rst
> +Edit the ``flask-mqtt-nginx/docker-compose.yml`` file and replace <factory> with your factory name:
This is no longer required. You can do images in compose like:
```
 image: hub.foundries.io/${FACTORY}/shellhttpd:latest
```
then people don't have to edit stuff

2021-07-28 15:54 UTC, doanac commented on source/tutorials/compose-app/compose-app-mosquitto-broker.rst
> +         restart: always
@Tim-Anderson - has been using `restart: unless-stopped` lately. I think that's a better rule to start sprinkling around in our docs for people to copy/paste

2021-07-28 15:54 UTC, doanac commented on source/tutorials/compose-app/compose-app-shellhttpd-mqtt.rst
> +The FondriesFactory CI will compile and publish it. Finally, the
```suggestion
The FoundriesFactory CI will build and publish the image. Finally, the 
```

2021-07-28 15:54 UTC, doanac commented on source/tutorials/compose-app/compose-app-shellhttpd-mqtt.rst
> +     RUN apk add --no-cache vim
```suggestion
     RUN apk add --no-cache mosquitto-clients vim
```
this will result in one less layer for docker to have to download

2021-08-10 13:08 UTC, vanmaegima requested changes

2021-08-10 13:08 UTC, vanmaegima commented on source/tutorials/compose-app/compose-app-flask-mqtt-nginx.rst
> +and configure the command to execute python3 with flask parameters.
```suggestion
and configures the command to execute python3 with flask parameters.
```

2021-08-10 13:08 UTC, vanmaegima commented on source/tutorials/compose-app/compose-app-flask-mqtt-nginx.rst
> +getting started with a flask example, instead of returning a  ``Hello World``,
```suggestion
getting started with flask examples, instead of returning a  ``Hello World``, 
```

2021-08-10 13:08 UTC, vanmaegima commented on source/tutorials/compose-app/compose-app-testing-applications.rst
> +the ``flask-mqtt-nginx_flask-mqtt_1`` will know who many accesses it had and
```suggestion
the ``flask-mqtt-nginx_flask-mqtt_1`` will know how many accesses it had and 
```

2021-08-10 13:08 UTC, vanmaegima commented on source/tutorials/compose-app/compose-app-summary.rst
> +This tutorial gives you a good overview of how the folder and files structure in
```suggestion
This tutorial gives you a good overview on how the folder and files structure in 
```

2021-08-10 20:02 UTC, doanac commented
Docs for 927e73faca6050a94d97a3706e8a587caac23500 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1025/docs/artifacts/html/index.html

2021-08-10 20:18 UTC, vanmaegima commented on source/tutorials/compose-app/compose-app-file-structure.rst
> +present in the same folder.
@munoz0raul this one is missing

2021-08-10 20:21 UTC, munoz0raul commented on source/tutorials/compose-app/compose-app-file-structure.rst
> +present in the same folder.
I accepted Andy's suggestion. It is in the same sentence. 

```
What is important in the example is the ``shellhttpd`` directory containing 
a ``docker-compose.yml`` and a ``Dockerfile`` file. CI will produce both a Docker Container image and Compose app named ``shellhttpd`
```

2021-08-11 11:15 UTC, vanmaegima commented on source/tutorials/compose-app/compose-app-flask-mqtt-nginx.rst
> +     app.config['MQTT_BROKER_URL'] = '192.168.15.11'
This comes from repo as: app.config['MQTT_BROKER_URL'] = 'host.docker.internal'

2021-08-11 11:17 UTC, vanmaegima commented on source/tutorials/compose-app/compose-app-testing-applications.rst
> +     129a54e5821b   hub.foundries.io/cavel/flask-mqtt        "python3 -m flask ru…"   10 minutes ago   Up 7 minutes                                 flask-mqtt-nginx_flask-mqtt_1
@munoz0raul flask didn't come up for me, but docker ps -a shows as exited:
`hub.foundries.io/vanessa-test/flask-mqtt        "python3 -m flask ru�…"   13 hours ago   Exited (1) 13 hours ago `

The only difference so far is in the MQTT_BROKER_URL and maybe `restart: unless-stopped` can influence as well. Can you please take a look?

2021-08-11 12:40 UTC, vanmaegima commented on source/tutorials/compose-app/compose-app-testing-applications.rst
> +    device:~$ docker logs -f flask-mqtt-nginx_flask-mqtt_1
```
io@imx8mmevk:~$ docker logs -f flask-mqtt-nginx_flask-mqtt_1
 * Serving Flask app 'app.py' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/flask/__main__.py", line 3, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 990, in main
    cli.main(args=sys.argv[1:])
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 596, in main
    return super().main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 845, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 321, in __init__
    self._load_unlocked()
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 346, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 402, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 256, in locate_app
    __import__(module_name)
  File "/srv/app.py", line 18, in <module>
    mqtt = Mqtt(app)
  File "/usr/lib/python3.9/site-packages/flask_mqtt/__init__.py", line 104, in __init__
    self.init_app(app)
  File "/usr/lib/python3.9/site-packages/flask_mqtt/__init__.py", line 183, in init_app
    self._connect()
  File "/usr/lib/python3.9/site-packages/flask_mqtt/__init__.py", line 209, in _connect
    res = self.client.connect(
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3546, in _create_socket_connectin
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable

```

2021-08-11 13:43 UTC, vanmaegima commented on source/tutorials/compose-app/compose-app-testing-applications.rst
> +     129a54e5821b   hub.foundries.io/cavel/flask-mqtt        "python3 -m flask ru…"   10 minutes ago   Up 7 minutes                                 flask-mqtt-nginx_flask-mqtt_1
this was resolved by adding 'restart: unless-stopped' to flask-mqtt-nginx/docker-compose.yml

2021-08-11 13:43 UTC, vanmaegima commented on source/tutorials/compose-app/compose-app-flask-mqtt-nginx.rst
> +         extra_hosts:
```suggestion
         image: hub.foundries.io/${FACTORY}/flask-mqtt:latest
         restart: unless-stopped
         extra_hosts:
```

2021-08-12 01:26 UTC, doanac commented
Docs for c83716611794d04cc0138f4958f176c4b9f64232 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1027/docs/artifacts/html/index.html

2021-08-12 12:30 UTC, vanmaegima approved these changes
LGTM

2021-08-12 20:56 UTC, Tim-Anderson approved these changes
After correcting the comments I made it should be okay to integrate LGTM

2021-08-12 20:56 UTC, Tim-Anderson commented on source/tutorials/compose-app/compose-app-applications.rst
> +To give you a practical experience this tutorial will guide you over three
drop 'To give you a practical experience' and capitalize 'this'

2021-08-12 20:56 UTC, Tim-Anderson commented on source/tutorials/compose-app/compose-app-flask-mqtt-nginx.rst
> +The Dockerfile start creating a layer from the latest
starts by creating

2021-08-12 21:14 UTC, doanac commented
Docs for af5d8ac3b53e12a6352001ad50e243b240575da2 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1038/docs/artifacts/html/index.html

2021-08-12 21:23 UTC, doanac commented
Docs for dda089ffb9279faacdab359ef5621cfcdd019278 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1039/docs/artifacts/html/index.html

2021-08-12 21:27 UTC, merged