reference-manual: boards: Added am64xx-sk flashing instructions
foundriesio/docs pull request #219
Opened 2021-05-11 21:31 UTC by Tim-Anderson

This provides the flashing instructions for the Texas Instruments AM64x SKEVM board.

Signed-off-by: Tim Anderson <tim.anderson@foundries.io>

2021-05-11 22:41 UTC, doanac commented
Docs for ccabee864d4a1b1434c5e5004caa098705d42272 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/891/docs/artifacts/html/index.html

2021-05-12 12:26 UTC, vanmaegima approved these changes

2021-05-12 12:29 UTC, angolini approved these changes

2021-05-12 18:24 UTC, doanac commented
Docs for 5f064c62b88ef209938b9bb7282dcbdc60ed9fb6 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/893/docs/artifacts/html/index.html

2021-05-12 21:54 UTC, munoz0raul approved these changes
LGTM

2021-05-12 23:45 UTC, Tim-Anderson commented
@MatthewCroughan can you please look at this and comment/approve? thanks in advance

2021-05-13 16:13 UTC, MatthewCroughan requested changes

2021-05-13 16:13 UTC, MatthewCroughan commented on source/reference-manual/boards/am64xx-sk.rst
> +Remove the micro SDCard from the host and insert it into the socket on the bottom of the board.
```suggestion
1. Remove the micro SDCard from the host and insert it into the socket on the bottom of the board.
```

2021-05-13 16:13 UTC, MatthewCroughan commented on source/reference-manual/boards/am64xx-sk.rst
> +Power on the board to boot the new image.
```suggestion
2. Power on the board to boot the new image.
```

2021-05-13 16:30 UTC, Tim-Anderson commented on source/reference-manual/boards/am64xx-sk.rst
> +Power on the board to boot the new image.
the step numbers are consistent with the other board installation instructions. Are you suggesting that all of them not have step numbers?

2021-05-13 16:54 UTC, Tim-Anderson commented on source/reference-manual/boards/am64xx-sk.rst
> +Power on the board to boot the new image.
done

2021-05-13 16:55 UTC, doanac commented
Docs for a5f59fa7b69393aea84418bf34463c06988e14c3 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/896/docs/artifacts/html/index.html

2021-05-13 17:12 UTC, merged