Customizing the Platform
foundriesio/docs pull request #222
Opened 2021-05-18 23:19 UTC by munoz0raul

2021-05-20 20:07 UTC, doanac commented
Docs for cb5f60af02d2dc0bd52e3d28c983fac30bfc9382 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/923/docs/artifacts/html/index.html

2021-05-20 21:44 UTC, doanac commented
Docs for 4eddb40b9bc35e8c7fa4554ab48a101099d90661 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/924/docs/artifacts/html/index.html

2021-05-21 15:42 UTC, vanmaegima approved these changes

2021-05-21 15:42 UTC, vanmaegima commented on source/tutorials/customizing-the-platform/customizing-the-platform.rst
> +Customizations in the platform usually are necessary when your need to add new
Customizations in the platform usually are necessary when **you** need to add new

2021-05-21 15:42 UTC, vanmaegima commented on source/tutorials/customizing-the-platform/customizing-the-platform.rst
> +  FoundriesFactory CI will help makeing it simple by building the platform in the cloud.
making

2021-05-21 15:42 UTC, vanmaegima commented on source/tutorials/customizing-the-platform/cloning-meta-sub-repository.rst
> +   When your Factory is first created, 2 branches are established: ``master`` and ``devel``.
2 branches are established for meta-subscriber-overrides

2021-05-21 18:15 UTC, angolini requested changes
I've added suggestions.
The only thing that I think it's critical to change is when using "Yocto" instead of "the Yocto Project"

2021-05-21 18:15 UTC, angolini commented on source/tutorials/customizing-the-platform/testing-recipe.rst
> +    ● shellhttpd.service - Start up Shellhttpd Application
● 
Could you, please, double check this character?

2021-05-21 18:15 UTC, angolini commented on source/tutorials/customizing-the-platform/testing-recipe.rst
> +Using a second terminal, test your applications using ``curl`` in any external
```suggestion
Using a second terminal, test your application using ``curl`` in any external 
```

2021-05-21 18:15 UTC, angolini commented on source/tutorials/customizing-the-platform/testing-recipe.rst
> +updates, the device needs to reboot.
Maybe include this "OSTree" information in this tutorial is too complex.
I think line 4 and 5 can be excluded.
The link 7 is talking about the need of a reboot, so I think it's ok

2021-05-21 18:46 UTC, doanac commented
Docs for b1c9d0f0f7eab26ad4b9b6fe18920295d2e037c2 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/927/docs/artifacts/html/index.html

2021-05-21 18:51 UTC, munoz0raul commented on source/tutorials/customizing-the-platform/customizing-the-platform.rst
> +All the previous tutorials covered the application development with Docker Compose Application.
I will remove this line, It is not necessary!

2021-05-21 19:44 UTC, munoz0raul commented on source/tutorials/customizing-the-platform/customizing-the-platform.rst
> +also allowed to customize and change the platform according to your needs.
I will wait for Mike review. He will probably change this line. In my sentence, I tried to cover any customization. On your suggestion, you are covering just adding the app. So, let's way Mike and Tim here.

2021-05-21 19:44 UTC, munoz0raul commented on source/tutorials/customizing-the-platform/customizing-the-platform.rst
> +reference hardwares and you have the total control to customize and change your platform.
Changed it!

2021-05-21 19:45 UTC, munoz0raul commented on source/tutorials/customizing-the-platform/customizing-the-platform.rst
> +Foundries.io updates in the Linux microPlatform also don't automatically apply
Changed!

2021-05-21 20:02 UTC, doanac commented
Docs for b890cd68deb5c95096f268e30d18b076ea27ff52 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/928/docs/artifacts/html/index.html

2021-05-25 20:18 UTC, doanac commented
Docs for 0e81312361df6a8ddd6d3f7c2dc486f49e6da437 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/935/docs/artifacts/html/index.html

2021-07-28 04:47 UTC, doanac commented
Docs for 3043357d89a0685745c9ce02ac95008ac95e8f25 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1004/docs/artifacts/html/index.html

2021-07-28 14:31 UTC, angolini approved these changes

2021-08-12 18:01 UTC, munoz0raul commented on source/tutorials/customizing-the-platform/customizing-the-platform.rst
> +also allowed to customize and change the platform according to your needs.
@Tim-Anderson could you take a look on this part as well.

2021-08-12 19:53 UTC, doanac commented
Docs for 79939cdb478a3a4bdecacbbaeb3493b2c656d3cb are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1036/docs/artifacts/html/index.html

2021-08-17 21:31 UTC, Tim-Anderson reviewed
correct my comments and it should be good to go

2021-08-17 21:31 UTC, Tim-Anderson commented on source/tutorials/customizing-the-platform/customizing-the-platform.rst
> +Foundries.io frequently update the Linux microPlatform for the reference hardwares;
updates

2021-08-17 21:31 UTC, Tim-Anderson commented on source/tutorials/customizing-the-platform/customizing-the-platform.rst
> +This tutorial guides you over simple ``meta-subscriber-overrides`` customization.
guides you through

2021-08-17 21:31 UTC, Tim-Anderson commented on source/tutorials/customizing-the-platform/shellhttpd-recipe.rst
> +    host:~$ git remote add fio https://github.com/munoz0raul/extra-meta-subscriber-overrides.git
is the repository in your private path munoz0raul ?

2021-08-19 19:46 UTC, doanac commented
Docs for a9822d371b45eeb40611d1570e18930e5f8474d8 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1075/docs/artifacts/html/index.html

2021-08-19 20:02 UTC, doanac commented
Docs for 42fbdcfb2f01f2fc39cca85470f37e3f2eb81a3f are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1076/docs/artifacts/html/index.html

2021-08-19 20:07 UTC, merged