Tutorial Working with Tags
foundriesio/docs pull request #226
Opened 2021-05-27 02:21 UTC by munoz0raul

2021-05-27 02:23 UTC, doanac commented
Docs for f35ac1299477872ff19326af63013f4321b7d700 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/939/docs/artifacts/html/index.html

2021-05-31 14:23 UTC, angolini approved these changes
I only added few changes, and I note on the summary. Nice information there!

2021-05-31 14:23 UTC, angolini commented on source/tutorials/working-with-tags/tagging-specific-version.rst
> +Because your device was configured to follow ``tutorial``, it should is probably
it should is probably -> it looks like there are some additional words, I meant, would it be "It should probably be" or "it is probably" or "it should be"?

2021-05-31 14:23 UTC, angolini commented on source/tutorials/working-with-tags/working-with-tags-summary.rst
> +  - Do not try and move devices backward by "untagging" **Targets**.
I think this information deserves a section, instead of being here in the summary.

And, I'm not sure I understand what happens when I untag a target. I thought nothing would change and now I'm confused.

2021-05-31 14:23 UTC, angolini commented on source/tutorials/working-with-tags/working-with-tags-summary.rst
> +``tutorial`` was based on the ``devel`` branch and the device was updating to newer versions.
I don't understand this sentence.

2021-05-31 14:59 UTC, doanac commented on source/tutorials/working-with-tags/working-with-tags.rst
> +there is brief explanation about tag.
```suggestion
there is brief explanation about tags.
```

2021-05-31 16:12 UTC, doanac commented on source/tutorials/working-with-tags/working-with-tags.rst
> +- Create more ``containers-devel`` **Targets**.
I don't have a better suggestion, but i keep pausing when i see "containers-devel" and "platform-devel" and then "devel" and start to think they are 3 different things. Maybe we can somehow emphasize that we are making changes to the container's devel branch to create new targets. And then this goal is more trigger builds to create devel tagged Targets?

2021-07-28 01:06 UTC, doanac commented
Docs for 948954fb64d81317a42390760708d1d3ff85df20 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1000/docs/artifacts/html/index.html

2021-07-28 04:24 UTC, doanac commented
Docs for f06c5d4f8c6b242fe6ce7a2d6ca8d6cd7b335714 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1001/docs/artifacts/html/index.html

2021-07-28 04:26 UTC, munoz0raul commented on source/tutorials/working-with-tags/working-with-tags-summary.rst
> +  - Do not try and move devices backward by "untagging" **Targets**.
Let's see what Mike says.

2021-07-28 04:29 UTC, doanac commented
Docs for 18c39c2b8827609ff77b54182998cfd08f330853 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1002/docs/artifacts/html/index.html

2021-07-28 14:35 UTC, doanac commented on source/tutorials/working-with-tags/working-with-tags.rst
> +``platform-devel``, a ``platform`` buid based on ``devel`` branch, and install it on the device.
```suggestion
``platform-devel``, a ``platform`` build based on ``devel`` branch, and install it on the device.
```

2021-07-28 14:42 UTC, munoz0raul commented on source/tutorials/working-with-tags/working-with-tags.rst
> +- Create more ``containers-devel`` **Targets**.
@doanac I don't know if you noticed but I also changed a bit this part and added a screen shot.

2021-07-28 15:12 UTC, doanac reviewed
Pretty interesting. It might be worth the effort of a "working with tags" to add a section for a more advanced flow like a doing a `containers-feature-x` branch that's based on `devel` platform builds. It would incorporate ideas from https://docs.foundries.io/82/reference-manual/ota/advanced-tagging.html

2021-07-28 15:12 UTC, doanac commented on source/tutorials/working-with-tags/creating-targets.rst
> +    host:~$ git push
maybe just this, so there's less to copy/paste?
``` 
git commit -m "This is the TEST 02" shellhttpd/docker-compose.yml
git push
```

2021-07-28 15:12 UTC, doanac commented on source/tutorials/working-with-tags/working-with-tags-summary.rst
> +  - Do not try and move devices backward by "untagging" **Targets**.
I think this summary is just bringing up an orthogonal topic. Just a nice quick summary like the first sentence.

2021-08-10 13:43 UTC, vanmaegima requested changes

2021-08-10 13:43 UTC, vanmaegima commented on source/tutorials/working-with-tags/inspecting-targets.rst
> +Base on the **Target** version listed above, the device should be running version ``9``.
```suggestion
Based on the **Target** version listed above, the device should be running version ``9``.
```

2021-08-10 13:43 UTC, vanmaegima commented on source/tutorials/working-with-tags/adapting-shellhttpd.rst
> +Make sure you received your update by checking the latest **Target** on the :guilabel:`Devices` tab
I believe in this step we should suggest the user to wait for their build, is that correct?
```suggestion
Wait for your build to finish by checking the latest **Target** on the :guilabel:`Devices` tab 
```

2021-08-10 13:43 UTC, vanmaegima commented on source/tutorials/working-with-tags/adapting-shellhttpd.rst
> +``devel`` will keep updating to the latest **Target**.
```suggestion
Whenever you change the ``devel`` branch, FoundriesFactory CI will build 
and generate a new **Target** tagged with ``devel``. As a result, devices following 
``devel`` will update to the latest **Target**.
```

2021-08-10 13:43 UTC, vanmaegima commented on source/tutorials/working-with-tags/following-specific-tag.rst
> +Note that now, version 10 is tagged with ``devel`` and ``tutorial``.
```suggestion
Note that version 10 is now tagged with ``devel`` and ``tutorial``.
```

2021-08-10 13:43 UTC, vanmaegima commented on source/tutorials/working-with-tags/creating-targets.rst
> +**Target** your device tagged with ``tutorial`` should update to.
```suggestion
Imagine, you will keep developing on ``devel`` but you want to decide which 
**Target** your device tagged with ``tutorial`` should update to.
```

2021-08-10 13:43 UTC, vanmaegima commented on source/tutorials/working-with-tags/creating-targets.rst
> +The lastest ``devel`` **Target** is also tagged with ``tutorial``.
```suggestion
The latest ``devel`` **Target** is also tagged with ``tutorial``.
```

2021-08-10 13:43 UTC, vanmaegima commented on source/tutorials/working-with-tags/creating-targets.rst
> +Keep watching your jobs on https://app.foundries.io and once it finishes changing
```suggestion
Keep watching your jobs on https://app.foundries.io and once it finishes, change
```

2021-08-10 13:43 UTC, vanmaegima commented on source/tutorials/working-with-tags/creating-targets.rst
> +    host:~$ git commit -m "This is the TEST 02"
```suggestion
    host:~$ git commit -m "This is the TEST 03"
```

2021-08-10 13:43 UTC, vanmaegima commented on source/tutorials/working-with-tags/creating-targets.rst
> +    host:~$ git commit -m "This is the TEST 02"
```suggestion
    host:~$ git commit -m "This is the TEST 04"
```

2021-08-10 13:43 UTC, vanmaegima commented on source/tutorials/working-with-tags/tagging-specific-version.rst
> +Because your device was configured to follow ``tutorial``, it should probably be
```suggestion
Because your device is configured to follow ``tutorial``, it should probably be
```

2021-08-10 13:43 UTC, vanmaegima commented on source/tutorials/working-with-tags/working-with-tags-summary.rst
> +``tutorial`` was based on the ``devel`` branch and the device was updating to newer versions.
I believe we can delete this phrase, the first one is much better and enough to understand the context.
```suggestion
```

2021-08-10 13:43 UTC, vanmaegima commented on source/tutorials/working-with-tags/working-with-tags-summary.rst
> +That been said:
```suggestion
That being said:
```

2021-08-10 13:43 UTC, vanmaegima commented on source/tutorials/working-with-tags/working-with-tags-summary.rst
> +could cause unexpected behaviors to the device.
```suggestion
could cause unexpected behaviors to the device. The suggestion is to keep your device
moving forward and do not update to earlier versions.
```

2021-08-12 18:27 UTC, munoz0raul commented on source/tutorials/working-with-tags/inspecting-targets.rst
> +
@doanac I don't have the same factory to get the logs as well as I think this tutorial is too long already. I leave how it is for now.

2021-08-12 18:36 UTC, doanac commented
Docs for 1b1fbef95caaea5973a0d915257ff0b31c14e207 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1032/docs/artifacts/html/index.html

2021-08-12 19:30 UTC, doanac approved these changes

2021-08-12 19:51 UTC, doanac commented
Docs for b1e1d89c156932907f9ef64ee299fce442bd9484 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1035/docs/artifacts/html/index.html

2021-08-13 15:31 UTC, vanmaegima approved these changes

2021-08-17 22:14 UTC, Tim-Anderson approved these changes
a few comments but otherwise looks good

2021-08-17 22:14 UTC, Tim-Anderson commented on source/tutorials/working-with-tags/tagging-specific-version.rst
> +    host:~$ fioctl targets tag --by-version -T devel,tutorial 12 -f
I do not think you want the -f on the command

2021-08-19 20:11 UTC, doanac commented
Docs for 1a6ad9343c70a1e177a4ae7780cf07653d1887a0 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1077/docs/artifacts/html/index.html

2021-08-19 20:14 UTC, doanac commented
Docs for 75c44d64fddc36111cd4bd4b94c1eaccffaeca14 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1078/docs/artifacts/html/index.html

2021-08-19 20:19 UTC, merged