rm: linux: Add a section on OSS compliance
foundriesio/docs pull request #228
Opened 2021-05-27 19:43 UTC by angolini

This PR is the conversion of #220 to MkDocs

The only significant change is that the subsections:

    INCOMPATIBLE_LICENSE
    IMAGE_LICENSE_CHECKER_ROOTFS_BLACKLIST

are real subsections now.

And I hope the conversion is as expected

2021-05-27 19:44 UTC, doanac commented
Docs for e0fa5a5da672959babe75ad32d1ecc3fcc7a2bc3 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/945/mkdocs/artifacts/index.html

2021-05-27 21:02 UTC, MatthewCroughan requested changes
This is really great. Thanks for contributing to the MkDocs branch so quickly. 

There are just some changes I've suggested that you can merge using the Github UI and then squash later.

2021-05-27 21:02 UTC, MatthewCroughan commented on mkdocs/docs/reference-manual/linux/linux-oss-compliance.md
> +    It is be possible to use packages under GPLv3 to `mfgtool` targets only.
```suggestion
    it is possible to enable or disable `DISABLE_GPLV3` on `mfgtool` targets as shown above.
```

2021-05-28 15:19 UTC, angolini commented
Thanks @MatthewCroughan  for the great review!

2021-05-28 15:20 UTC, doanac commented
Docs for 922f5b5d02797120e93239445987bb0a0357ec28 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/946/mkdocs/artifacts/index.html

2021-05-28 19:21 UTC, doanac commented
Docs for 13b3d73c761c0f0dc418b886f7a942b9503db488 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/949/mkdocs/artifacts/index.html

2021-05-28 20:46 UTC, MatthewCroughan commented
LGTM :hammer:

2021-05-28 20:46 UTC, MatthewCroughan approved these changes
LGTM :hammer:

2021-05-31 13:20 UTC, merged