rm: factory: Add ci-scripts notes
foundriesio/docs pull request #256
Opened 2021-08-17 17:35 UTC by angolini

Signed-off-by: Daiane Angolini <daiane.angolini@foundries.io>

2021-08-17 17:37 UTC, doanac commented
Docs for 93215b953dcabaa8496b5a14327f33ec8b7adb30 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1064/docs/artifacts/html/index.html

2021-08-17 17:42 UTC, vanmaegima requested changes

2021-08-17 17:42 UTC, vanmaegima commented on source/reference-manual/factory/factory-sources.rst
> +        * The git history from **ci-scripts.git** cannot be override (force push is disabled).
```suggestion
        * The git history from **ci-scripts.git** cannot be overriden (force push is disabled).
```

2021-08-17 17:56 UTC, MrCry0 commented on source/reference-manual/factory/factory-sources.rst
> +        * The git history from **ci-scripts.git** cannot be override (force push is disabled).
> 

@vanmaegima Maybe `overridden`?

2021-08-17 18:02 UTC, doanac commented
Docs for 41ea5b96fa4469053e1f9bd594399c1cfbfa0f26 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1065/docs/artifacts/html/index.html

2021-08-17 22:38 UTC, Tim-Anderson approved these changes
LGTM

2021-08-17 23:04 UTC, angolini commented on source/reference-manual/factory/factory-sources.rst
> +        * The git history from **ci-scripts.git** cannot be override (force push is disabled).
the new version does not have this word so I'm solving this

2021-08-18 13:54 UTC, vanmaegima approved these changes
LGTM

2021-08-18 14:13 UTC, munoz0raul approved these changes
LGTM

2021-08-18 15:15 UTC, merged