FAQ improvements
foundriesio/docs pull request #260
Opened 2021-08-24 19:05 UTC by vanmaegima

A set of information helpful for subscribers.

2021-08-24 19:06 UTC, doanac commented
Docs for dd4568568a34613e46a247c11ab2e5b6292fb483 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1086/docs/artifacts/html/index.html

2021-08-24 20:33 UTC, Tim-Anderson requested changes

2021-08-24 20:33 UTC, Tim-Anderson commented on source/reference-manual/troubleshooting/troubleshooting.rst
> +    sudo bash -c 'printf "[uptane]\npolling_sec = <time-sec>" > /etc/sota/conf.d/z-01-polling.toml'
it might be better if you use the same files names in both examples. This is z-01 and the next is z-90

2021-08-24 23:11 UTC, ricardosalveti commented on source/reference-manual/troubleshooting/troubleshooting.rst
> +    sudo bash -c 'printf "[uptane]\npolling_sec = <time-sec>" > /etc/sota/conf.d/z-01-polling.toml'
bash might not be available by default (on systems without gplv3), so better to just use sh (but test with busybox's sh here to be sure it still works as expected).

2021-08-24 23:11 UTC, ricardosalveti commented on source/reference-manual/troubleshooting/troubleshooting.rst
> +    SUMMARY = "Start up Application"
I would change summary to 'SOTA configuration fragment' or similar.

2021-08-24 23:13 UTC, ricardosalveti commented on source/reference-manual/troubleshooting/troubleshooting.rst
> +    compose_apps = ""
I don't think we need this pacman piece, only update / polling_sec should be enough (as this will also disable docker prune by default, which is not what you're covering here.

2021-08-24 23:14 UTC, ricardosalveti commented on source/reference-manual/troubleshooting/troubleshooting.rst
> +    OSTREE_KERNEL_ARGS_<machine> = "console=${console} <new-args> ${OSTREE_KERNEL_ARGS_COMMON}"
Please add a line explaining what is the default content from OSTREE_KERNEL_ARGS_COMMON.

OSTREE_KERNEL_ARGS_COMMON is not necessarily needed on devices specifying the partition path directly with 'root='.

2021-08-24 23:16 UTC, ricardosalveti commented on source/reference-manual/troubleshooting/troubleshooting.rst
> +    ExecStart=/usr/bin/<service-name>.sh
You're installing as '${D}${bindir}/<service-name>', so drop the .sh from this line (or install with .sh).

2021-08-24 23:17 UTC, ricardosalveti commented
Some minor comments but thanks for extending the FAQ!

2021-08-25 12:02 UTC, doanac commented
Docs for 81a458825beb04268c6f4e0e888c7e660123d2e6 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1087/docs/artifacts/html/index.html

2021-08-25 13:07 UTC, vanmaegima commented on source/reference-manual/linux/linux-extending.rst
> +    layer, it can be removed with ``CORE_IMAGE_BASE_INSTALL_remove = <package>``.
@angolini What if we used IMAGE_INSTALL_remove? Will that work for every package?

2021-08-25 14:13 UTC, vanmaegima commented on source/reference-manual/linux/linux-extending.rst
> +    layer, it can be removed with ``CORE_IMAGE_BASE_INSTALL_remove = <package>``.
decided with @angolini to drop this change from the PR

2021-08-25 14:13 UTC, doanac commented
Docs for d993e6cd4435c6639fffaf7b199e9a1cdb929d66 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1090/docs/artifacts/html/index.html

2021-08-25 14:37 UTC, Tim-Anderson approved these changes
LGTM

2021-08-25 15:31 UTC, ricardosalveti approved these changes
LGTM

2021-08-25 15:53 UTC, merged