Zynqmp boot software updates
foundriesio/docs pull request #314
Opened 2022-02-02 19:26 UTC by igoropaniuk

2022-02-02 19:46 UTC, doanac commented
Docs for 083c7596c7aa5af0081869b2432a6833b32c764c are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1264/docs/artifacts/html/index.html

2022-02-03 12:45 UTC, MrCry0 commented on source/reference-manual/security/boot-software-updates-imx.rst
> +In some cases, SoC may have embedded firmware (such as DDR firmware for
This paragraph confuses me a little. It would be better to add information on what and from where loads this embedded SoC firmware.

2022-02-03 14:00 UTC, vanmaegima commented on source/reference-manual/security/boot-software-updates-zynqmp.rst
> +To do that just **lmp-boot-firmware.bbappend** to your *meta-subscriber*
```suggestion
To do that just **lmp-boot-firmware.bbappend** to your *meta-subscriber-overrides*
```

2022-02-03 15:15 UTC, igoropaniuk commented on source/reference-manual/security/boot-software-updates-imx.rst
> +In some cases, SoC may have embedded firmware (such as DDR firmware for
this is a document I wasn't working on, it was just moved to a different file.

2022-02-03 15:22 UTC, doanac commented
Docs for 51898e731d50194e059c3761641c776f22ecae7c are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1265/docs/artifacts/html/index.html

2022-02-03 15:24 UTC, doanac commented
Docs for b650e61bc65677975b30e4c99054a767e9b9b93e are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1266/docs/artifacts/html/index.html

2022-02-04 14:15 UTC, doanac commented
Docs for 7338a279b5f27206f505fabb8b8a2b14d92b6c5e are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1269/docs/artifacts/html/index.html

2022-02-04 14:29 UTC, MrCry0 approved these changes
LGTM

2022-02-04 14:43 UTC, angolini approved these changes
Only minor suggestions. Great PR

2022-02-04 14:43 UTC, angolini commented on source/reference-manual/security/boot-software-updates-imx.rst
> +DDR firmware for mx8m). This firmware is loaded prior to the load /
```suggestion
DDR firmware for i.MX 8M). This firmware is loaded prior to the load /
```

2022-02-06 23:35 UTC, kprosise requested changes
Due to the combined length of these documents, reviewing is going to take longer and usual. As such, I will be making suggestions in two or more batches.

2022-02-06 23:35 UTC, kprosise commented on source/reference-manual/security/boot-software-updates-imx.rst
> +and U-Boot FIT deployment steps:
```suggestion
To deploy boot images to the destination board, the mfgtools package is used.
It uses a special configuration file with uuu extensions, which contains
all needed instructions for the deployment of boot images. Default
uuu files do not support flashing images for secondary boot path. Doing so requiring
the following adjustments: adding SIT image, secondary SPL
and U-Boot FIT deployment steps:
```

2022-02-06 23:35 UTC, kprosise commented on source/reference-manual/security/boot-software-updates-imx.rst
> +So the final uuu script looks like:
```suggestion
The final uuu script looks like:
```

2022-02-06 23:35 UTC, kprosise commented on source/reference-manual/security/boot-software-updates-imx.rst
> +regular **lmp.cfg**:
```suggestion
To enable support for flashing/booting secondary boot images,
adjust the default **lmp.cfg** and  the one for mfgtools  for the device, enabling
support for the secondary boot path.

The following config options need to be added to the default **lmp.cfg**:
```

2022-02-08 17:03 UTC, doanac commented
Docs for 7842c9662683dee6ab3abd1b3c47f0b0932f717b are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1281/docs/artifacts/html/index.html

2022-02-08 17:09 UTC, doanac commented
Docs for 4540787a8ef8653430dd58462866504dcdac9afb are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1282/docs/artifacts/html/index.html

2022-02-08 17:11 UTC, igoropaniuk commented
All existing comments are addressed.

2022-02-08 17:12 UTC, igoropaniuk commented on source/reference-manual/security/boot-software-updates-zynqmp.rst
> +This artifact may be signed (on closed boards) as a part of CI and
dropped that `on closed boards` completely

2022-02-08 17:13 UTC, igoropaniuk commented on source/reference-manual/security/boot-software-updates-imx.rst
> +SPL is the first software loader generated by the i.MX U-Boot build. It
quickly checked, looks like i.MX with dot is correct one (`https://en.wikipedia.org/wiki/I.MX`)

2022-02-08 18:28 UTC, kprosise approved these changes

2022-02-08 18:32 UTC, vanmaegima approved these changes
just a single comment but LGTM

2022-02-08 18:32 UTC, vanmaegima commented on source/reference-manual/security/boot-software-updates-imx.rst
> +To do that just **lmp-boot-firmware.bbappend** to your *meta-subscriber*
```suggestion
To do that just **lmp-boot-firmware.bbappend** to your *meta-subscriber-overrides*
```

2022-02-08 19:26 UTC, ricardosalveti approved these changes
LGTM, quite a long one, but quite nice to see this documented.

2022-02-08 19:31 UTC, kprosise commented
There is only minor changes here and there that I would suggest to conform with the style-guide, but nothing seems deal breaking, and they can be done later as part of my documentation clean up. If the technical content looks okay, I'm okay with approving this.

2022-02-08 20:46 UTC, merged

2022-02-08 20:48 UTC, doanac commented
Docs for 9f76e82a8dbbc7ba514b44036dd2f161ceb388fb are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1286/docs/artifacts/html/index.html