Reorg flash page
foundriesio/docs pull request #529
Opened 2023-04-28 18:52 UTC by angolini

## Readiness

* [x] Draft

## Overview

The goal is to get the maximum text reuse for the flashing pages by using variables to replace some key texts.

There are a few questions I'm still wondering about:

* Should the base file be split into more than one file?
* is there a better way to handle the -sec variant?
* Should I take this opportunity to change the text flow, or should I first refactor the pages and review the content when the new mfgtool is in place (and I will need to review the step-by-step?)

I will also work on the other boards (and expand this PR), but it would be good to have some early feedback.

2023-04-28 18:53 UTC, doanac commented
Docs for f89298098b7ea8ae8bcaaee9a5b5172efabc4da8 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2074/docs/artifacts/html/index.html

2023-05-04 15:35 UTC, kprosise commented
@angolini I hope to get to this soon, I am excited to check it out!

2023-05-16 04:30 UTC, kprosise approved these changes
Looks good! I made some fairly minor suggestions, but nothing major. You rock!

2023-05-16 04:30 UTC, kprosise commented on source/reference-manual/boards/imx-common-board-sec.inc
> +Factory.
```suggestion
.. important::
Ensure you replace the ``<factory>`` placeholder below with the name of your
Factory.
```

2023-05-16 04:30 UTC, kprosise commented on source/reference-manual/boards/imx-common-board-sec.inc
> +Factory.
```suggestion
.. important::
   Ensure you replace the ``<factory>`` placeholder below with the name of your Factory.
```

2023-05-16 04:30 UTC, kprosise commented on source/reference-manual/boards/imx-common-board-sec.inc
> +#. Download necessary files from ``https://app.foundries.io/factories/<factory>/targets``
```suggestion
#. Download the necessary files from ``https://app.foundries.io/factories/<factory>/targets``
```

2023-05-16 04:30 UTC, kprosise commented on source/reference-manual/boards/imx-common-board-sec.inc
> +#. Extract the file ``lmp-factory-image-<machine_name>.wic.gz``::
```suggestion
#. Extract ``lmp-factory-image-<machine_name>.wic.gz``::
```

2023-05-16 04:30 UTC, kprosise commented on source/reference-manual/boards/imx-common-board-sec.inc
> +#. Download and extract the file ``mfgtool-files-<machine_name>.tar.gz``::
```suggestion
#. Download and extract ``mfgtool-files-<machine_name>.tar.gz``::
```

2023-05-16 04:30 UTC, kprosise commented on source/reference-manual/boards/imx-common-board-sec.inc
> +#. **OPTIONAL**—Only required if you have problems and/or want to see the boot console output.
```suggestion
#. **OPTIONAL**—Only required if you have problems or want to see the boot console output.
```

2023-05-16 04:30 UTC, kprosise commented on source/reference-manual/boards/imx-common-board-sec.inc
> +Once in serial downloader mode and connected to your PC the evaluation board
```suggestion
Once in serial downloader mode and connected to your PC, the evaluation board
```

2023-05-16 04:30 UTC, kprosise commented on source/reference-manual/boards/imx-common-board.inc
> +Factory.
```suggestion
.. important::
   Ensure you replace the ``<factory>`` placeholder below with the name of your Factory.
```

2023-05-16 04:30 UTC, kprosise commented on source/reference-manual/boards/imx-common-board.inc
> +#. Extract the file ``lmp-factory-image-<machine_name>.wic.gz``::
```suggestion
#. Extract ``lmp-factory-image-<machine_name>.wic.gz``::
```

2023-05-16 04:30 UTC, kprosise commented on source/reference-manual/boards/imx-common-board.inc
> +#. Download and extract the file ``mfgtool-files-<machine_name>.tar.gz``::
```suggestion
#. Download and extract ``mfgtool-files-<machine_name>.tar.gz``::
```

2023-05-16 04:30 UTC, kprosise commented on source/reference-manual/boards/imx-common-board.inc
> +#. **OPTIONAL**—Only required if you have problems and/or want to see the boot console output.
```suggestion
#. **OPTIONAL**—Only required if you have problems or want to see the boot console output.
```

2023-05-16 04:30 UTC, kprosise commented on source/reference-manual/boards/imx-common-board.inc
> +     On a Linux host for example:
```suggestion
     For example, on a Linux host:
```

2023-05-16 04:30 UTC, kprosise commented on source/reference-manual/boards/imx6ull.rst
> +---------------
```suggestion
Prepreparation
--------------
```

2023-05-16 14:28 UTC, doanac commented
Docs for 882763112b34f09a5a89d292efd6736afeeca04d are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2112/docs/artifacts/html/index.html

2023-05-24 17:40 UTC, Tim-Anderson commented
for the 6ull under `Organize all the files like the tree below` the lmp-factory-image incorrectly contains a `.gz` at the end but a previous step was to decompress it so it should just end in a `.wic`

The other note, is that some *-prepare.rst have `<machine-name>` and others have the machine spelled out. we should be consistent.

2023-06-13 11:12 UTC, kprosise commented
@angolini Just wanted to check in and see where we are on this! Let me know when it is ready for a final review and merge!

2023-06-13 15:00 UTC, angolini commented
@kprosise I still have some changes to upload, it is not ready for final review/merge.

2023-06-30 20:51 UTC, doanac commented
Docs for f444128afc6aa449863067bbcf7e839b7f8789b6 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2242/docs/artifacts/html/index.html

2023-06-30 21:09 UTC, Tim-Anderson requested changes
inline comments

2023-06-30 21:09 UTC, Tim-Anderson commented on source/reference-manual/boards/imx6ul.rst
> +          ├── lmp-factory-image-imx6ulevk.wic.gz
Please remove the .gz from this line since previous step was to unzip

2023-06-30 21:09 UTC, Tim-Anderson commented on source/reference-manual/boards/imx6ull.rst
> +          ├── lmp-factory-image-imx6ullevk.wic.gz
Same here, remove .gz

2023-06-30 21:09 UTC, Tim-Anderson commented on source/reference-manual/boards/imx8ulpevk.rst
> +          ├── lmp-factory-image-imx8ulp-lpddr4-evk.wic.gz
no .gz

2023-06-30 21:16 UTC, doanac commented
Docs for 13fd92be0cdf3c5b713fb834aa1141c75a4b61e6 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2243/docs/artifacts/html/index.html

2023-06-30 21:23 UTC, doanac commented
Docs for 408d975c3813fe9500e174392732ba845fa68160 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2244/docs/artifacts/html/index.html

2023-06-30 21:24 UTC, angolini commented
> for the 6ull under `Organize all the files like the tree below` the lmp-factory-image incorrectly contains a `.gz` at the end but a previous step was to decompress it so it should just end in a `.wic`
> 
> The other note, is that some *-prepare.rst have `<machine-name>` and others have the machine spelled out. we should be consistent.

@Tim-Anderson, for imx6 ULL and imx6 UL they are both using the generic file, and I could get parsed-literal working to replace the |machine-name|. However, it has different formatting (white background). In some other places, I let the formation rule only (examples). Please take a look if this is enough.

2023-07-03 08:47 UTC, merged