ug: ts: add information about orphan targets
foundriesio/docs pull request #547
Opened 2023-06-23 18:15 UTC by vanmaegima

## Readiness

* [ ] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

_Why merge this PR? What does it solve?_

## Checklist

_Optional. Add a 'x' to steps taken._
_You can fill this out after opening the PR. "Did I..."_

* [ ] Run spelling and grammar check, preferably with linter.
* [ ] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [ ] Match tone and style of page/section.
* [ ] Run `make linkcheck`.
* [ ] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [ ] follow best practices for commits.
  * [ ] Descriptive title written in the imperative.
  * [ ] Include brief overview of QA steps taken.
  * [ ] Mention any related issues numbers.
  * [ ] End message with sign off/DCO line (`-s, --signoff`).
  * [ ] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [ ] Squash commits if needed.
* [ ] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._
_This could include potential issues, rational for approach, etc._

2023-06-23 18:17 UTC, doanac commented
Docs for f9ed3befbe46f35ae58f26ee6a6a60899a3b0a57 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2193/docs/artifacts/html/index.html

2023-06-23 18:36 UTC, doanac commented
Docs for c77586128ce662e50ae588b5c074e6b58cb27f17 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2194/docs/artifacts/html/index.html

2023-06-23 18:54 UTC, doanac commented
Docs for 814af950b20e7d85cee8cc4782d6a51b2b0c339e are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2195/docs/artifacts/html/index.html

2023-06-23 18:57 UTC, doanac commented
Docs for 8298a17a6d1d8aa512f24058a54f890fc4e17aa7 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2196/docs/artifacts/html/index.html

2023-06-23 20:13 UTC, angolini approved these changes
Only few minor suggestions

2023-06-23 20:13 UTC, angolini commented on source/user-guide/offline-update/offline-update.rst
> +A customer client should handle this case if it is not the intended behavior.
Do you mean "customer's client"? In this case, maybe "This is not the intended behavior and should be implemented in a custom client application" sounds better.

2023-06-23 20:13 UTC, angolini commented on source/user-guide/offline-update/offline-update.rst
> +Both cases can work together, but the offline update feature was initially designed to be offline only until the device was registered. Constantly toggling between online and offline mode is not some
I suggest inverting the order to bring the most important sentence to the beginning:

Toggling between online and offline modes is not tested or validated by Foundries.io. It should be handled by a custom client application. Both cases can work together, but the offline update feature was initially designed to be offline only until the device was registered.

2023-06-23 20:13 UTC, angolini commented on source/user-guide/offline-update/offline-update.rst
> +There are a few points to take into account by the customer client:
```suggestion
There are a few points to take into account by the custom client application:
```

2023-06-23 20:13 UTC, angolini commented on source/user-guide/offline-update/offline-update.rst
> +   * **The key rule is not run two types of updates/clients simultaneously**: ``aktualizr-lite`` should be stopped before ``aklite-offline`` runs and vice-versa.
```suggestion
   * **The critical rule is not to run two types of updates/clients simultaneously**: ``aktualizr-lite`` should be stopped before ``aklite-offline`` runs and vice-versa.
```

2023-06-23 20:13 UTC, angolini commented on source/user-guide/offline-update/offline-update.rst
> +   * Offline Update can downgrade version: A client around the offline updater should check it out and decide whether to allow downgrade or not.
```suggestion
   * Offline Update can downgrade version: A client around the offline updater should check it out and decide whether to allow a downgrade or not.
```

2023-06-23 20:13 UTC, angolini commented on source/user-guide/troubleshooting/troubleshooting.rst
> +Targets list for that Tag.
I'm not sure which "tag" and "target" words would be formated as code-in-text in this paragraph

2023-06-23 20:25 UTC, Tim-Anderson requested changes
This appears to be 2 different topics in the same PR. The title implies only orphans would be described but this also has updates to preloads and oe_builtins which have nothing to do with orphans.

I suggest this be split into 2 PRs

2023-06-27 11:12 UTC, kprosise commented
With the overlapping pages on container preloading, I suggest we go with keeping the info in the reference manual page

2023-06-27 15:56 UTC, vkhoroz commented on source/user-guide/troubleshooting/troubleshooting.rst
> +* A device runs an old Target that has been pruned from the Targets list.
The third use case is when a device switches from one tag to another tag, and is running a target version which is not present in a new tag.

2023-06-27 15:56 UTC, vkhoroz commented on source/user-guide/troubleshooting/troubleshooting.rst
> +* A user creates a wave for Target 42 and some devices are updated. The user then cancels the wave, removing Target 42 from the Targets list. A new wave is created for Target 43. Running ``fioctl wav
It is strange to see the reference to Waves in CI targets, as waves only manage production targets.

So, I propose to move this content into the `targets.rst` document; which talks about targets in general, and already has a section for the `factory status` command.

Also, this bullet needs to explicitly state that it is only applicable to production devices (targets).

2023-06-28 18:12 UTC, vanmaegima commented on source/user-guide/troubleshooting/troubleshooting.rst
> +* A user creates a wave for Target 42 and some devices are updated. The user then cancels the wave, removing Target 42 from the Targets list. A new wave is created for Target 43. Running ``fioctl wav
@vkhoroz This is currently on the troubleshooting page, should we move everything to the `targets.rst` file?

2023-06-28 18:14 UTC, vanmaegima commented on source/user-guide/troubleshooting/troubleshooting.rst
> +* A user creates a wave for Target 42 and some devices are updated. The user then cancels the wave, removing Target 42 from the Targets list. A new wave is created for Target 43. Running ``fioctl wav
I added a note about being applicable to only production targets.

2023-06-28 18:16 UTC, vanmaegima commented
> With the overlapping pages on container preloading, I suggest we go with keeping the info in the reference manual page

@kprosise should I drop the UG page in this PR?

2023-06-28 18:22 UTC, doanac commented
Docs for aff57cb83984bf28a2e4e51dc625172e751db773 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2224/docs/artifacts/html/index.html

2023-06-28 21:28 UTC, vkhoroz commented on source/user-guide/troubleshooting/troubleshooting.rst
> +* A user creates a wave for Target 42 and some devices are updated. The user then cancels the wave, removing Target 42 from the Targets list. A new wave is created for Target 43. Running ``fioctl wav
Sorry @vanmaegima 
I thought it's on ci-targets.rst page... somehow I was blinded.

Troubleshooting is fine.

2023-06-29 10:56 UTC, kprosise commented
> > With the overlapping pages on container preloading, I suggest we go with keeping the info in the reference manual page
> 
> @kprosise should I drop the UG page in this PR?

Perhaps a separate PR would be easier, as we would also need to add the appropriate redirect. I would be happy to do it. Of course, if you would rather just do it as part of this one, that is totally fine with me.

2023-06-29 11:44 UTC, vanmaegima commented
@kprosise let's leave for the next one, it would be better if you could handle it as you're aware of all the needs there :)

2023-06-29 11:47 UTC, kprosise commented
@vanmaegima, sounds good, I'll create a separate issue for removing the UG page. Let me know when you are ready to merge this PR!

2023-06-29 11:48 UTC, kprosise approved these changes
Looks good!

2023-06-29 11:54 UTC, doanac commented
Docs for 6bdbaab4889c1a048607a41ff083e3278d27f66c are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2227/docs/artifacts/html/index.html

2023-06-29 12:06 UTC, vanmaegima commented on source/user-guide/offline-update/offline-update.rst
> +Related to the bullet above, Foundries.io® cannot provide secure delivery of offline update content since the customer should do the packaging and delivery.
@kprosise do you know why this is failing?

2023-06-30 16:09 UTC, Tim-Anderson reviewed
The content looks good on all the pages, consider moving the `offline considerations` more towards the top of the page

2023-06-30 16:09 UTC, Tim-Anderson commented on source/user-guide/offline-update/offline-update.rst
> +Offline Update Considerations
I am wondering if this section should be closer to the top of this page. before someone actually tries to set this up

2023-07-03 14:22 UTC, vanmaegima commented on source/user-guide/offline-update/offline-update.rst
> +   Make sure to check the :ref:`Offline Update Considerations`.
@Tim-Anderson I added a note here as I didn't want to add an introduction to this page.
@kprosise What do you think?

2023-07-03 14:23 UTC, doanac commented
Docs for 62908f8ce3984e5d646ad7496d45a7f6c6e37f23 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2245/docs/artifacts/html/index.html

2023-07-04 13:35 UTC, kprosise commented on source/user-guide/offline-update/offline-update.rst
> +   Make sure to check the :ref:`Offline Update Considerations`.
I approve!

2023-07-04 13:37 UTC, kprosise commented on source/user-guide/offline-update/offline-update.rst
> +Related to the bullet above, Foundries.io® cannot provide secure delivery of offline update content since the customer should do the packaging and delivery.
```suggestion
Related to the bullet above, Foundries.io™ cannot provide secure delivery of offline update content since the customer should do the packaging and delivery.
```

2023-07-04 14:59 UTC, doanac commented
Docs for 480010ebb17bba8516f909068d96383d042a8f81 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2249/docs/artifacts/html/index.html

2023-07-04 15:09 UTC, vanmaegima commented
@kprosise ready to merge

2023-07-04 15:14 UTC, merged