Add new guide to help those that are looking for to emulate instead o…
foundriesio/docs pull request #605
Opened 2023-09-23 10:21 UTC by camilamacedo86

…f use physical boards

## Readiness

* [x] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

Upon following the guides, it is unclear whether the steps in the "Flashing Your Device" section are the same as those required to emulate with QEMU. Additionally, each factory requires a unique set of artefacts, and the command to run with QEMU varies.

When just getting started, users likely do not concern themselves with the specifics of the platform; they simply want to understand how the solution works. Therefore, this PR proposes adding a new guide to allow users to easily copy and paste commands, flash an image with QEMU, and proceed to the next tutorials.

Also, we are adding notes to clarify:

![Screenshot 2023-09-23 at 11 20 45](https://github.com/foundriesio/docs/assets/7708031/da80146b-10bb-469a-b6b3-b7671986ca22)
![Screenshot 2023-09-23 at 11 20 32](https://github.com/foundriesio/docs/assets/7708031/1d3f5e48-93ba-4473-a9ae-c80520222260)

## Checklist

_Optional. Add a 'x' to steps taken._
_You can fill this out after opening the PR. "Did I..."_

* [ ] Run spelling and grammar check, preferably with linter.
* [ ] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [ ] Match tone and style of page/section.
* [ ] Run `make linkcheck`.
* [ ] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [ ] follow best practices for commits.
  * [ ] Descriptive title written in the imperative.
  * [ ] Include brief overview of QA steps taken.
  * [ ] Mention any related issues numbers.
  * [ ] End message with sign off/DCO line (`-s, --signoff`).
  * [ ] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [ ] Squash commits if needed.
* [ ] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._
_This could include potential issues, rational for approach, etc._

2023-09-23 10:23 UTC, doanac commented
Docs for 0606461d3bd28d8a2f845220313e385b3447701f are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2358/docs/artifacts/html/index.html

2023-09-23 10:36 UTC, doanac commented
Docs for f5dc007be28571e7f10a222cb819d0487d81bae5 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2359/docs/artifacts/html/index.html

2023-09-23 10:42 UTC, doanac commented
Docs for 709704d589ea60857e320298cc90e0fe48e4f2b6 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2360/docs/artifacts/html/index.html

2023-09-23 10:46 UTC, doanac commented
Docs for 582b6be8429a488649b68de7c7a2c00cdc3ed260 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2361/docs/artifacts/html/index.html

2023-09-23 22:01 UTC, doanac commented
Docs for 9cd46e657029510003ba69aec18a04c01ac6e19d are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2362/docs/artifacts/html/index.html

2023-09-25 13:29 UTC, angolini approved these changes
It looks like to me that it would be good to have a link to this pages added to https://docs.foundries.io/latest/getting-started/flash-device/index.html

I would use hard wrap based on semantic line breaks

But those are only suggestions. LGTM

2023-09-25 13:29 UTC, angolini commented on source/index.rst
> +   getting-started/emulation-with-qemu/index
I would add this step before building-deploying-app, as I think we can choose to test QEMU without changing the source code (if one chooses it as the main machine for the factory)

2023-09-25 13:38 UTC, vanmaegima commented
I'm a bit concerned that we will start to duplicate information with this PR, making the docs hard to maintain.
We had a discussion in the past about making all of out Getting Started steps using QEMU. I would rather go this way than creating a new page like this.

2023-09-25 13:42 UTC, vanmaegima requested changes

2023-09-25 13:42 UTC, vanmaegima commented on source/getting-started/emulation-with-qemu/index.rst
> +  This tutorial is designed to assist you in getting started with using QEMU to emulate devices on your desktop. Please note that we are selecting a specific FoundriesFactory® to establish an environ
```suggestion
  This tutorial is designed to assist you in getting started with using QEMU to emulate devices on your desktop. Please note that we are selecting a specific FoundriesFactory® to establish an environment for experimenting with the Foundries.io® solution. This approach will enable you to engage with subsequent tutorials and enhance your skills.
```

2023-09-25 13:42 UTC, vanmaegima commented on source/getting-started/emulation-with-qemu/index.rst
> +   - Ensure that you have installed `QEMU <https://www.qemu.org/download/>`_.
One other example of maintainability: QEMU only works for us starting in version X.Y which is mentioned in another page.

2023-09-25 13:42 UTC, vanmaegima commented on source/getting-started/emulation-with-qemu/index.rst
> +1. Go to the `Targets` tab of your Factory and download the ``lmp-base-console-image-qemuarm64-secureboot.wic.gz`` image and the ``flash.bin``:
It's odd that we are recommending `lmp-base-console-image` here. Shouldn't it be `lmp-factory-image`?

2023-09-25 13:42 UTC, vanmaegima commented on source/getting-started/emulation-with-qemu/index.rst
> +   :alt: Artefacts which are required to run the image with QEMU
```suggestion
   :alt: Artifacts which are required to run the image with QEMU
```

2023-09-25 13:42 UTC, vanmaegima commented on source/getting-started/emulation-with-qemu/index.rst
> +3. Copy the Artefacts to the ``lmp-qemu/arm64`` directory :
```suggestion
3. Copy the Artifacts to the ``lmp-qemu/arm64`` directory :
```

2023-09-25 13:42 UTC, vanmaegima commented on source/getting-started/emulation-with-qemu/index.rst
> +   :alt: Artefacts which are required to run the image with QEMU
We also have steps to download with fioctl, which are mentioned in the QEMU pages

2023-09-25 13:42 UTC, vanmaegima commented on source/getting-started/flash-device/index.rst
> +   If you are just getting started and prefer to emulate the device rather than using a physical board, make sure to refer to the guide :ref:`gs-emulation-with-qemu`. Following this guide will lead y
I like this note, but I would prefer to fix the QEMU page and point it there rather than creating a whole new page.

2023-09-25 13:43 UTC, vanmaegima commented
My suggestion would be to fix the content in https://docs.foundries.io/latest/reference-manual/qemu/arm64.html (as well as other QEMU pages) for better support, then point this page in the getting started.

2023-09-25 15:54 UTC, camilamacedo86 commented on source/getting-started/emulation-with-qemu/index.rst
> +   :alt: Artefacts which are required to run the image with QEMU
@vanmaegima, we have some instructions in place for downloading the image. However, it's important to note that each factory requires the use of specific artifacts – they are not all the same. The QEMU page provides generic information, but our goal here is to offer a comprehensive example, covering all steps from A to Z. By doing so, we hope to streamline the process, enabling users to simply copy, paste, and get things running. This approach aims to save users from spending unnecessary hours trying to figure out which specific artefact to download for a particular factory and determining the exact command arguments to use in each case.

However, let me know where we have the exactly same step and we can create a template to avoid the user need to navigate in so many links

2023-09-25 15:56 UTC, camilamacedo86 commented on source/getting-started/emulation-with-qemu/index.rst
> +   - Ensure that you have installed `QEMU <https://www.qemu.org/download/>`_.
OK, I will try to find out this info. 
thank you

2023-09-25 16:04 UTC, camilamacedo86 commented on source/getting-started/emulation-with-qemu/index.rst
> +1. Go to the `Targets` tab of your Factory and download the ``lmp-base-console-image-qemuarm64-secureboot.wic.gz`` image and the ``flash.bin``:
that is the image that I am using and it is working
If that is not the right one could you please guide me in what image should I use?

2023-09-25 16:08 UTC, camilamacedo86 commented on source/getting-started/flash-device/index.rst
> +   If you are just getting started and prefer to emulate the device rather than using a physical board, make sure to refer to the guide :ref:`gs-emulation-with-qemu`. Following this guide will lead y
"We are unable to modify the QEMU page as it is designed to provide generic information applicable to all factories. The challenge arises when individuals are getting started; they typically want to follow a guide that is straightforward and works seamlessly. However, the artifacts, flags, and other parameters vary from one factory to another, making the process more complex.

I personally spent over a day trying to figure out how to run it, a duration that could have been reduced to less than 15 minutes had there been a more specific and tailored documentation available.

So the goal of this doc is to give to you guidance to experiment the product and follow up the tutorials
Then, want you to know that and want to do that for specific factory the generic info in the QEMU pages are useful to help you out.

2023-09-25 16:12 UTC, doanac commented
Docs for dc09c24567c6e848dc66364ca25346640cdee0cd are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2363/docs/artifacts/html/index.html

2023-09-25 16:15 UTC, doanac commented
Docs for 1eeeb60d1a734ca6df298ed644998750e4b0bc58 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2364/docs/artifacts/html/index.html

2023-09-25 16:36 UTC, vanmaegima commented on source/getting-started/emulation-with-qemu/index.rst
> +1. Go to the `Targets` tab of your Factory and download the ``lmp-base-console-image-qemuarm64-secureboot.wic.gz`` image and the ``flash.bin``:
@camilamacedo86 This actually might be alright due to the fast first target stuff, I'll double check in a bit.
Context is: usually `lmp-base-console-image` is what we get from a local LmP build while `lmp-factory-image` is the default from a factory. Now we have fast first target from the public LmP builds so this is actually correct. I'll resolve this comment, you can ignore it!

2023-09-25 16:36 UTC, vanmaegima commented on source/getting-started/flash-device/index.rst
> +   If you are just getting started and prefer to emulate the device rather than using a physical board, make sure to refer to the guide :ref:`gs-emulation-with-qemu`. Following this guide will lead y
I was thinking of this page: https://docs.foundries.io/latest/reference-manual/qemu/arm64.html
We could modify it for better and simpler instructions.
We indeed do not support multiple use cases of QEMU. We have customers doing special use cases and using custom parameters and it's on them to support. Happy to discuss in a call if you feel I got this wrong.
The other discussion the docs team were having is to have the whole getting started facing QEMU, maybe @kprosise can let us know the status here, I think this would simplify the whole getting started session.

2023-09-25 16:37 UTC, vanmaegima commented on source/getting-started/emulation-with-qemu/index.rst
> +   - Ensure that you have installed `QEMU <https://www.qemu.org/download/>`_.
Just found it, QEMU version 5.2: https://docs.foundries.io/latest/reference-manual/qemu/arm64.html#booting-in-qemu

2023-09-25 16:45 UTC, vanmaegima commented on source/getting-started/emulation-with-qemu/index.rst
> +  This tutorial is designed to assist you in getting started with using QEMU to emulate devices on your desktop. Please note that we are selecting a specific FoundriesFactory® to establish an environ
I think this will fix the build error:
```suggestion
  This tutorial is designed to assist you in getting started with using QEMU to emulate devices on your desktop. Please note that we are selecting a specific FoundriesFactory® to establish an environment for experimenting with the Foundries.io™ solution. This approach will enable you to engage with subsequent tutorials and enhance your skills.
```

2023-09-25 17:46 UTC, doanac commented
Docs for 22f03de7b79270ff9755074d5ac00c6b186b2d6e are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2365/docs/artifacts/html/index.html

2023-09-25 17:49 UTC, doanac commented
Docs for 2317e9cdaccfcc53f2945b0696dbbff70a8cad8e are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2366/docs/artifacts/html/index.html

2023-09-25 17:54 UTC, doanac commented
Docs for a36ac67621337c9f0656647bb1e778ae36c860bc are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2367/docs/artifacts/html/index.html

2023-09-25 17:58 UTC, doanac commented
Docs for a7ce8d3515bcd88e823cf8f9ca3baa3dc69dae35 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2368/docs/artifacts/html/index.html

2023-09-26 07:20 UTC, doanac commented
Docs for 1ece67557c6c27a4575cda34d25a5cd81bd494f4 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2370/docs/artifacts/html/index.html

2023-09-26 12:04 UTC, MrCry0 approved these changes
LGTM

2023-09-26 14:33 UTC, kprosise reviewed
I like this addition! I left some suggestions, mostly related to markup style, which doesn't change how it is rendered.
One additional note: I would move `reference-manual/qemu/emulation-with-qemu/` to `getting-started/emulation-with-qemu/`

2023-09-26 14:33 UTC, kprosise commented on source/reference-manual/qemu/emulation-with-qemu/index.rst
> +  This tutorial is designed to assist you in getting started with using QEMU to emulate devices on your desktop. Please note that we are selecting a specific FoundriesFactory® to establish an environ
```suggestion
  This tutorial is designed to assist you in getting started with using QEMU to emulate devices on your desktop.
  Please note that we are selecting a specific machine to establish an environment for experimenting with FoundriesFactory®.
  This approach will enable you to engage with subsequent tutorials and enhance your skills.
```

2023-09-26 14:33 UTC, kprosise commented on source/reference-manual/qemu/emulation-with-qemu/index.rst
> +   - Create a :ref:`ref-factory` for the platform ``QEMU Arm 64 bit`` as described in the guide :ref:`gs-select-platform`:
```suggestion
   - Create a :ref:`ref-factory` for the ``QEMU Arm 64 bit`` platform as described in the guide :ref:`gs-select-platform`:
```

2023-09-26 14:33 UTC, kprosise commented on source/reference-manual/qemu/emulation-with-qemu/index.rst
> +Use ``qemu-img`` to convert your raw disk image to the QCOW2 format. This step can sometimes make the image more amenable to virtualization.
```suggestion
Use ``qemu-img`` to convert your raw disk image to the QCOW2 format.
This step can sometimes make the image more amenable to virtualization.
```

2023-09-26 14:33 UTC, kprosise commented on source/reference-manual/qemu/emulation-with-qemu/index.rst
> +Resize the new QCOW2 image to a size that’s a multiple of the sector size. Let’s resize it to 4GB for simplicity.
```suggestion
Resize the new QCOW2 image to a size that’s a multiple of the sector size.
Let us resize it to 4GB for simplicity.
```

2023-09-26 14:33 UTC, kprosise commented on source/reference-manual/qemu/emulation-with-qemu/index.rst
> +   By default, the ``username`` and ``password`` to log in your device after boot are ``fio/fio``. We recommend changing them once you are in development.
```suggestion
   By default, the ``username`` and ``password`` to log in your device after boot are ``fio/fio``.
   We recommend changing them once you are in development.
```

2023-09-26 14:33 UTC, kprosise commented on source/reference-manual/qemu/emulation-with-qemu/index.rst
> +   If you encounter a QEMU terminal where common commands like ``ls`` are unresponsive, it may indicate an issue. A missing login prompt likely means that your image did not boot successfully.
```suggestion
   If you encounter a QEMU terminal where common commands like ``ls`` are unresponsive, it may indicate an issue.
   A missing login prompt likely means that your image did not boot successfully.
```

2023-09-26 14:33 UTC, kprosise commented on source/reference-manual/qemu/emulation-with-qemu/index.rst
> +   For this specific platform, we use the ``-bios=flash.bin`` flag to boot the system. However, the flags and configurations may vary based on the selected platform.
```suggestion
   For this specific platform, we use the ``-bios=flash.bin`` flag to boot the system.
   However, the flags and configurations may vary based on the selected platform.
```

2023-09-26 14:33 UTC, kprosise commented on source/reference-manual/qemu/emulation-with-qemu/index.rst
> +At this point, you have successfully set up the device. You are now able to :ref:`gs-register` and proceed with the following tutorials.
```suggestion
At this point, you have successfully set up the device.
You are now able to :ref:`gs-register` and proceed with the following tutorials.
```

2023-09-26 14:33 UTC, kprosise commented on source/reference-manual/qemu/qemu.rst
> +   If you're just starting and prefer emulation, refer to the guide :ref:`gs-emulation-with-qemu`. This guide achieves the same result as :ref:`gs-flash-device`. Afterward, you can proceed with the s
```suggestion
   If you're just starting and prefer emulation, refer to the guide :ref:`gs-emulation-with-qemu`.
   This guide achieves the same result as :ref:`gs-flash-device`.
   Afterward, you can proceed with the subsequent steps to :ref:`gs-register`.
```

2023-09-27 07:46 UTC, camilamacedo86 commented on source/getting-started/emulation-with-qemu/index.rst
> +   :alt: Artefacts which are required to run the image with QEMU
I am marking this one as solved but let me know if you think that we should change it out.

2023-09-27 08:23 UTC, doanac commented
Docs for 3193818ebc0a3b93964e1cd3b506bca0ce82fa26 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2372/docs/artifacts/html/index.html

2023-09-27 11:32 UTC, doanac commented
Docs for cb13ca40f7bb6fe15dfa813f2e70614fd7d10163 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2374/docs/artifacts/html/index.html

2023-09-28 14:35 UTC, kprosise approved these changes
LGTM. I will proceed with merging! Thank you for doing this!

2023-09-28 14:35 UTC, merged