rm: boards: am62xx-evk: update flashing instructions
foundriesio/docs pull request #607
Opened 2023-09-29 11:45 UTC by igoropaniuk

Update flashing instructions, as new flash.sh script is used for flash automation.

## Readiness

* [ ] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

_Why merge this PR? What does it solve?_

## Checklist

_Optional. Add a 'x' to steps taken._
_You can fill this out after opening the PR. "Did I..."_

* [ ] Run spelling and grammar check, preferably with linter.
* [ ] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [ ] Match tone and style of page/section.
* [ ] Run `make linkcheck`.
* [ ] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [ ] follow best practices for commits.
  * [ ] Descriptive title written in the imperative.
  * [ ] Include brief overview of QA steps taken.
  * [ ] Mention any related issues numbers.
  * [ ] End message with sign off/DCO line (`-s, --signoff`).
  * [ ] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [ ] Squash commits if needed.
* [ ] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._
_This could include potential issues, rational for approach, etc._

2023-09-29 11:48 UTC, doanac commented
Docs for ce210be14caca7154b96c389a813f2075b9db4d4 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2375/docs/artifacts/html/index.html

2023-09-29 11:52 UTC, kprosise approved these changes
LGTM

2023-09-29 12:21 UTC, MrCry0 commented on source/reference-manual/boards/am62xx-sk.rst
> +Set up the board for booting from USD DFU mode:
`s/USD/USB/` ?

2023-09-29 12:44 UTC, angolini approved these changes
LGTM, only minor suggestions

2023-09-29 12:44 UTC, angolini commented on source/reference-manual/boards/am62xx-sk.rst
> +    dfu-util: can't detach
I have no idea why can't have a red box:
![image](https://github.com/foundriesio/docs/assets/1568936/23c2aafe-7b07-45b1-9db8-1ab0936c6c03)

2023-09-29 15:20 UTC, Tim-Anderson requested changes
I think the point of using DFU was to flash to eMMC not to an SD card.

2023-09-29 15:20 UTC, Tim-Anderson commented on source/reference-manual/boards/am62xx-sk.rst
> +   changing boot switches to: ``01000000 11000010``.
Should't the flashing be into the eMMC and not an SD card?

2023-10-02 13:54 UTC, igoropaniuk commented on source/reference-manual/boards/am62xx-sk.rst
> +   changing boot switches to: ``01000000 11000010``.
nice catch, actually script is flashing to eMMC card (I confused with `stm32-mfgtool-files` for `stm32mp15-disco`). Rewriting the article

2023-10-02 14:26 UTC, igoropaniuk commented on source/reference-manual/boards/am62xx-sk.rst
> +   using ``flash.sh`` script from ``ti-mfgtool-files-am62xx-evm`` directory.
fixed

2023-10-02 14:26 UTC, igoropaniuk commented on source/reference-manual/boards/am62xx-sk-prepare.rst
> +      ├── lmp-factory-image-am62xx-evm.wic.gz
fixed

2023-10-02 14:26 UTC, igoropaniuk commented on source/reference-manual/boards/am62xx-sk.rst
> +   changing boot switches to: ``01000000 11000010``.
fixed

2023-10-02 14:27 UTC, igoropaniuk commented on source/reference-manual/boards/am62xx-sk.rst
> +Set up the board for booting from USD DFU mode:
fixed

2023-10-02 14:28 UTC, doanac commented
Docs for 35d3dd7fb7367fb6e063e858b7261d01e8dc42c0 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2380/docs/artifacts/html/index.html

2023-10-02 17:33 UTC, Tim-Anderson approved these changes
LGTM

2023-10-02 18:27 UTC, igoropaniuk commented
@kprosise I think we can merge it, thanks

2023-10-03 10:27 UTC, merged