Cleanup testing reference manual section
foundriesio/docs pull request #683
Opened 2024-02-04 10:42 UTC by kprosise

Applied style guide recommendations and edited to increase readability.

QA Steps: linter and spellcheck used in editor. Checked rendered output for correctness. No issues found.

This commit addresses FFTK-2796
This commit applies to FFTK-1702

# PR Template and Checklist

Please complete as much as possible to speed up the reviewing process.

Readiness and adding reviewers as appropriate is required.

All PRs should be reviewed by a technical writer/documentation team and a peer.
If effecting customers—which is a majority of content changes—a member of Customer Success must also review.

## Readiness

* [x] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

In addition to cleanup, also added an overview summary to the title/toc page for the section.

## Checklist

* [x] Run spelling and grammar check, preferably with linter.
* [x] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [x] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [x] Match tone and style of page/section.
* [ ] Run `make linkcheck`.
* [x] View HTML in a browser to check rendering.
* [x] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [x] follow best practices for commits.
  * [x] Descriptive title written in the imperative.
  * [x] Include brief overview of QA steps taken.
  * [x] Mention any related issues numbers.
  * [x] End message with sign off/DCO line (`-s, --signoff`).
  * [x] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [x] Squash commits if needed.
* [x] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._
_This could include potential issues, rational for approach, etc._

2024-02-04 10:45 UTC, doanac commented
Docs for 9729a522135a82521c769d67e037cf0eab66efe3 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2592/docs/artifacts/html/index.html

2024-02-05 11:06 UTC, mwasilew requested changes
I found 1 typo. Apart from that LGTM. Many thanks for doing that!

2024-02-05 11:06 UTC, mwasilew commented on source/reference-manual/testing/lmp-testplan.rst
> +For a release candidate buil,d additional manual tests are performed.
should be ``build, ``

2024-02-05 11:22 UTC, kprosise reviewed
address feedback

2024-02-05 11:22 UTC, kprosise commented on source/reference-manual/testing/lmp-testplan.rst
> +For a release candidate buil,d additional manual tests are performed.
```suggestion
For a release candidate build, additional manual tests are performed.
```

2024-02-05 11:22 UTC, kprosise commented on source/reference-manual/testing/lmp-testplan.rst
> +For a release candidate buil,d additional manual tests are performed.
weird, I recall seeing that while editing, and thought I had fixed it! Thanks for spotting it!

2024-02-05 11:24 UTC, doanac commented
Docs for afe6d8df58591e931b7ff9f1899e1e0004ce7641 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2593/docs/artifacts/html/index.html

2024-02-05 12:04 UTC, mwasilew approved these changes

2024-02-06 09:08 UTC, doanac commented
Docs for a547999e15f1effa8201addcbb932d4f7634463d are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2596/docs/artifacts/html/index.html

2024-02-06 09:26 UTC, merged