Clarify device group read-only permission
foundriesio/docs pull request #772
Opened 2024-11-18 14:50 UTC by kprosise

The documentation was reworded. The changes should help clarify that members with read-only permission can still view other groups and devices.

QA: Viewed rendered html, edited with linter plugin. Ran linkcheck.

This commit addresses ticket FFTK-3602, "clarify device group read permission details"

# PR Template and Checklist

Please complete as much as possible to speed up the reviewing process.

Readiness and adding reviewers as appropriate is required.

All PRs should be reviewed by a technical writer/documentation team and a peer.
If effecting customers—which is a majority of content changes—a member of Customer Success must also review.

## Readiness

* [x] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

Addresses point of confusion for customer

## Checklist

* [x] Run spelling and grammar check, preferably with linter.
* [x] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [x] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [x] Match tone and style of page/section.
* [x] Run `make linkcheck`.
* [x] View HTML in a browser to check rendering.
* [x] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [x] follow best practices for commits.
  * [x] Descriptive title written in the imperative.
  * [x] Include brief overview of QA steps taken.
  * [x] Mention any related issues numbers.
  * [x] End message with sign off/DCO line (`-s, --signoff`).
  * [x] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [x] Squash commits if needed.
* [x] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._
_This could include potential issues, rational for approach, etc._

2024-11-21 15:01 UTC, vanmaegima requested changes

2024-11-21 15:01 UTC, vanmaegima commented on source/user-guide/account-management/team-based-access.rst
> +They can only *see* the ``test-lab-devices`` group and devices included into it, they can not make any modifications.
I feel this is still a bit misleading. They can see all devices, but can only make modifications to devices in this device group. With the current sentence, they can still think they should be able to only see the devices in this device group.

2024-11-21 15:02 UTC, vanmaegima commented
Maybe under https://ci.foundries.io/projects/fio-docs/builds/2798/docs/artifacts/html/user-guide/account-management/team-based-access.html#team-based-access-to-device-groups we can do add a note or something saying that device and CI/targets view are available for all users.

2024-11-21 15:13 UTC, doanac commented
ci/targets can be blocked to a user in a team that's not given access to ci/targets. But a user in no team can view them

2024-11-22 10:00 UTC, kprosise commented
My mind is a bit jumbled now about what exactly we are trying to say. I will try to parse this all again soon.

2024-12-05 17:10 UTC, doanac commented
Docs for 38db7f0e6b362c2fff997935abb50e02de4b14f1 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2804/docs/artifacts/html/index.html

2024-12-05 19:16 UTC, vanmaegima commented on source/user-guide/account-management/team-based-access.rst
> +   The Device and CI/Targets view is available for all Factory users.
```suggestion
   The Device view is available for all Factory users.
```

ci/targets can be blocked based on tokens as reported by Andy.

2024-12-05 19:16 UTC, vanmaegima commented on source/user-guide/account-management/team-based-access.rst
> +    *  ``devices:read`` - permission to view the details and configuration of a device/group.
maybe?
```suggestion
    *  ``devices:read`` - permission to view the details and configuration of a device/group; set to all members of a factory.
```

2024-12-06 10:12 UTC, doanac commented
Docs for 293d758007e7f0119b87a9210d75ffd5c5826656 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2805/docs/artifacts/html/index.html

2024-12-06 12:55 UTC, vanmaegima approved these changes

2024-12-06 12:56 UTC, doanac commented
Docs for 546e1a50fd8ee5f161660d3c742b802acb0bb064 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2806/docs/artifacts/html/index.html

2024-12-06 15:41 UTC, merged